//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnApps.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLearnApps.Business.Resources.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///	   ad.AttendanceSessionId,
        ///     ad.[Percentage],
        ///     ad.AttendanceDataId,
        ///	   ats.AttendanceListId,
        ///     ad.UserId
        ///FROM 
        ///	AttendanceDatas ad
        ///    INNER JOIN AttendanceSessions ats 
        ///		ON ats.AttendanceSessionId = ad.AttendanceSessionId AND ats.AttendanceListId IN ({1}) AND ats.IsDeleted = 0
        ///
        ///  UNION
        ///
        ///SELECT 
        ///	ats.AttendanceSessionId,
        ///	0 AS [Percentage],
        ///	0 AS AttendanceDataId,
        ///	ats.AttendanceListId,
        ///  0 UserId
        ///FROM 
        ///	AttendanceSessions ats
        ///WHERE 
        ///	NOT EXISTS
        ///	(
        ///		SELECT 
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceData_GetAllStudentAttendanceDataByListIds {
            get {
                return ResourceManager.GetString("AttendanceData_GetAllStudentAttendanceDataByListIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ad.[AttendanceDataId]
        ///      ,ad.[AttendanceSessionId]
        ///      ,ad.[UserId]
        ///      ,ad.[Percentage]
        ///      ,ad.[Remarks]
        ///      ,ad.[LastUpdatedBy]
        ///      ,ad.[LastUpdatedTime]
        ///      ,ad.Participation
        ///      ,ad.Excused
        ///      ,ad.[IsDeleted] FROM AttendanceDatas ad WHERE ad.UserId = {0} AND ad.IsDeleted = 0 AND ad.AttendanceSessionId IN ({1}).
        /// </summary>
        internal static string AttendanceData_GetById {
            get {
                return ResourceManager.GetString("AttendanceData_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///	   ad.AttendanceSessionId,
        ///     ad.[Percentage],
        ///     ad.AttendanceDataId
        ///   ,ad.Participation
        ///      ,ad.Excused
        ///	   ,ats.AttendanceListId
        ///FROM 
        ///	AttendanceDatas ad
        ///    INNER JOIN AttendanceSessions ats 
        ///		ON ats.AttendanceSessionId = ad.AttendanceSessionId AND ad.UserId = {0} AND ats.AttendanceListId IN ({1}) AND ats.IsDeleted = 0
        ///.
        /// </summary>
        internal static string AttendanceData_GetDataForMyAttendanceDetail {
            get {
                return ResourceManager.GetString("AttendanceData_GetDataForMyAttendanceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ad 
        ///	SET  ad.[Percentage] = 0, ad.LastUpdatedBy = {0}, ad.LastUpdatedTime = GETUTCDATE()
        ///FROM
        ///	AttendanceDatas ad
        ///	INNER JOIN AttendanceSessions ats ON ats.AttendanceSessionId = ad.AttendanceSessionId AND ad.IsDeleted = 0 AND ad.[Percentage] IS NULL
        ///	INNER JOIN AttendanceLists al ON al.AttendanceListId = ats.AttendanceListId AND ats.IsDeleted = 0 AND al.CourseId = {1}
        ///WHERE 
        ///	(
        ///		  (
        ///			  ats.EntryCloseTime IS NULL AND ats.SessionStartTime &lt; GETUTCDATE()
        ///		  )
        ///		  OR
        ///		  (
        ///			  ats.Entry [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceData_UpdateAbsent {
            get {
                return ResourceManager.GetString("AttendanceData_UpdateAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRY
        ///  BEGIN TRANSACTION;
        ///    DECLARE @AttendanceListId AS int;
        ///    SET @AttendanceListId = {0};
        ///    CREATE TABLE #Temp (
        ///      AttendanceDataId int,
        ///      AttendanceSessionId int
        ///    );
        ///    BEGIN
        ///      INSERT INTO #Temp (AttendanceDataId,
        ///      AttendanceSessionId)
        ///        SELECT
        ///          ad.AttendanceDataId,
        ///          ad.AttendanceSessionId
        ///        FROM AttendanceDatas ad
        ///        INNER JOIN AttendanceSessions ats
        ///          ON ats.AttendanceSessionId = ad.AttendanceSessionId
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceList_Delete {
            get {
                return ResourceManager.GetString("AttendanceList_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT al.AttendanceListId FROM AttendanceLists al WHERE al.IsDeleted = 0 AND al.CourseId = {0}.
        /// </summary>
        internal static string AttendanceList_GetListId {
            get {
                return ResourceManager.GetString("AttendanceList_GetListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRY
        ///    BEGIN TRANSACTION;
        ///    DECLARE @AttendanceListId AS INT;
        ///    SET @AttendanceListId = {0};
        ///    CREATE TABLE #TempSession
        ///    (
        ///        AttendanceDataId INT
        ///    );
        ///    BEGIN
        ///        INSERT INTO #TempSession
        ///        (
        ///            AttendanceDataId
        ///        )
        ///        SELECT ad.AttendanceDataId
        ///        FROM AttendanceDatas ad
        ///            INNER JOIN AttendanceSessions ats
        ///                ON ats.AttendanceSessionId = ad.AttendanceSessionId
        ///                   AND ats.AttendanceListId =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceSession_DeleteSelected {
            get {
                return ResourceManager.GetString("AttendanceSession_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ads.[AttendanceSessionId]
        ///      ,ads.[AttendanceListId]
        ///      ,ads.[SessionStartTime]
        ///      ,ads.[EntryCloseTime]
        ///      ,ads.[LastUpdatedBy]
        ///      ,ads.[LastUpdatedTime]
        ///      ,ads.[IsDeleted] FROM AttendanceSessions ads WHERE ads.AttendanceListId = {0} AND ads.IsDeleted = 0 ORDER BY ads.SessionStartTime DESC.
        /// </summary>
        internal static string AttendanceSession_GetById {
            get {
                return ResourceManager.GetString("AttendanceSession_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///			ats.AttendanceSessionId, ats.AttendanceListId 
        ///		FROM AttendanceSessions ats
        ///			INNER JOIN AttendanceLists al ON al.AttendanceListId = ats.AttendanceListId AND ats.IsDeleted = 0 AND al.CourseId = {0}
        ///WHERE NOT EXISTS ( SELECT * FROM AttendanceDatas ad WHERE ad.AttendanceSessionId = ats.AttendanceSessionId AND ad.[Percentage] IS NOT NULl ) AND
        ///	(
        ///		  (
        ///			  ats.EntryCloseTime IS NULL AND ats.SessionStartTime &lt; GETUTCDATE()
        ///		  )
        ///		  OR
        ///		  (
        ///			  ats.EntryCloseTime IS NOT NULL AND ats.E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceSession_GetListExpired {
            get {
                return ResourceManager.GetString("AttendanceSession_GetListExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT cg.[Id]
        ///FROM CategoryGroups cg 
        ///	INNER JOIN UserGroups ug ON cg.Id = ug.CategoryGroupId
        ///	INNER JOIN UserEnrollments ue ON ue.UserId = ug.UserId AND ue.CourseId = {0} AND ue.UserId = {1}.
        /// </summary>
        internal static string CategoryGroup_GetGroupIdByCourseWithUser {
            get {
                return ResourceManager.GetString("CategoryGroup_GetGroupIdByCourseWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	cg.Id 
        ///FROM 
        ///	CategoryGroups cg 
        ///	INNER JOIN CourseCategories cc ON cg.CourseCategoryId = cc.Id AND cc.CourseId = {0} 
        ///	INNER JOIN UserEnrollments ue ON ue.CourseId = cc.CourseId AND ue.UserId = {1} AND ue.RoleId = {2}.
        /// </summary>
        internal static string CategoryGroup_GetIdByCondition {
            get {
                return ResourceManager.GetString("CategoryGroup_GetIdByCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT cg.[Id]
        ///      ,cg.[Name]
        ///      ,cg.[CourseCategoryId] 
        ///	  ,ug.[UserId]
        ///FROM CategoryGroups cg 
        ///	INNER JOIN UserGroups ug ON cg.Id = ug.CategoryGroupId
        ///	INNER JOIN UserEnrollments ue ON ue.UserId = ug.UserId AND ue.CourseId = {0}.
        /// </summary>
        internal static string CategoryGroup_GetListByCourse {
            get {
                return ResourceManager.GetString("CategoryGroup_GetListByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT cg.[Id]
        ///      ,cg.[Name]
        ///      ,cg.[CourseCategoryId]
        ///      ,&apos;&apos; AS SectionName
        ///	  ,ug.[UserId]
        ///FROM CategoryGroups cg 
        ///  INNER JOIN CourseCategories cc ON cc.Id = cg.CourseCategoryId AND cc.CourseId = {0}
        ///	INNER JOIN UserGroups ug ON cg.Id = ug.CategoryGroupId
        ///	INNER JOIN UserEnrollments ue ON ue.UserId = ug.UserId AND ue.CourseId = {0} AND ue.RoleId IN ({1}).
        /// </summary>
        internal static string CategoryGroup_GetListByCourseWithRole {
            get {
                return ResourceManager.GetString("CategoryGroup_GetListByCourseWithRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT cg.Id AS [Value], cg.[Name] AS [Text]  FROM CategoryGroups cg  WHERE cg.Id IN ({1}).
        /// </summary>
        internal static string CategoryGroup_GetListByGroupIds {
            get {
                return ResourceManager.GetString("CategoryGroup_GetListByGroupIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	SELECT DISTINCT
        ///       us.Id AS UserId,
        ///       cg.Id AS [Value],
        ///       cg.[Name] AS [Text],
        ///       etg.EvaluationPairingId
        ///FROM Users us
        ///    INNER JOIN UserEnrollments ue ON us.Id = ue.UserId
        ///    INNER JOIN UserGroups ug ON ug.UserId = us.Id
        ///    INNER JOIN CategoryGroups cg ON cg.Id = ug.CategoryGroupId
        ///    INNER JOIN CourseCategories cc ON cc.Id = cg.CourseCategoryId AND cc.CourseId = {0}
        ///    INNER JOIN EvaluationTargets etg ON etg.OrgUnitId = cg.Id
        ///           AND etg.EvaluationPairingId IN
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CategoryGroup_GetMyEvaluationResponseGroup {
            get {
                return ResourceManager.GetString("CategoryGroup_GetMyEvaluationResponseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.EvaluationId, e.EvaluationTypeId, e.[Name], e.CourseId , e.[Description] FROM Evaluations e WHERE e.IsDeleted = 0 AND e.CourseId = {3} AND e.[Name] LIKE N&apos;%{2}%&apos; ORDER BY e.LastUpdatedTime DESC OFFSET {0} * ({1} - 1) ROWS FETCH NEXT {0} ROWS ONLY;.
        /// </summary>
        internal static string Evaluation_GetEvaluationByCourse {
            get {
                return ResourceManager.GetString("Evaluation_GetEvaluationByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 	
        ///	b.UserId, d.Id AS OrgUnitId , a.OrgDefinedId, a.DisplayName AS [Name] 
        ///FROM 
        ///	Users a
        ///	INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.RoleId IN ({0}) AND b.CourseId = {1}
        ///	INNER JOIN CourseCategories c ON c.CourseId = b.CourseId
        ///	INNER JOIN CategoryGroups d ON c.Id = d.CourseCategoryId
        ///	INNER JOIN UserGroups e ON e.CategoryGroupId = d.Id AND e.UserId = b.UserId.
        /// </summary>
        internal static string Evaluation_GetInstructor {
            get {
                return ResourceManager.GetString("Evaluation_GetInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @UserId INT
        ///SET @UserId = {0}
        ///DECLARE @CourseId INT
        ///SET @CourseId = {1}
        ///DECLARE @EvaluationId INT
        ///SET @EvaluationId = {2}
        ///SELECT EP.EvaluationPairingId FROM Evaluations AS E
        ///INNER JOIN EvaluationPairings AS EP ON EP.EvaluationId = E.EvaluationId
        ///INNER JOIN EvaluationTargets AS ET ON	ET.EvaluationPairingId = EP.EvaluationPairingId
        ///WHERE E.CourseId = @CourseId AND ET.UserId = @UserId AND ET.IsOrgUnit = 0 AND EP.IsDeleted = 0 AND ET.IsDeleted = 0 AND E.EvaluationId = @EvaluationId
        ///UNION
        ///SELE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evaluation_GetListPairingId {
            get {
                return ResourceManager.GetString("Evaluation_GetListPairingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @UserId INT
        ///SET @UserId = {0}
        ///DECLARE @CourseId INT
        ///SET @CourseId = {1}
        ///SELECT E.EvaluationId,
        ///       E.CourseId,
        ///       E.Name,
        ///       E.Description,
        ///       E.EvaluationTypeId,
        ///       E.AllowSelfEvaluate,
        ///       E.IsInstructorEvaluator,
        ///       E.InstructorWeight,
        ///       E.AllowEvaluation,
        ///       E.QuestionScoreCalculation,
        ///       E.SessionScoreCalculation,
        ///       E.LastUpdatedBy,
        ///       E.LastUpdatedTime,
        ///       E.CreatedTime,
        ///       E.IsDeleted,
        ///       E.GradeObjectId,
        ///       E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evaluation_GetResult {
            get {
                return ResourceManager.GetString("Evaluation_GetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @UserId INT
        ///SET @UserId = {0}
        ///DECLARE @CourseId INT
        ///SET @CourseId = {1}
        ///DECLARE @EvaluationId INT
        ///SET @EvaluationId = {2}
        ///SELECT E.EvaluationId,
        ///       E.CourseId,
        ///       E.Name,
        ///       E.Description,
        ///       E.EvaluationTypeId,
        ///       E.AllowSelfEvaluate,
        ///       E.IsInstructorEvaluator,
        ///       E.InstructorWeight,
        ///       E.AllowEvaluation,
        ///       E.QuestionScoreCalculation,
        ///       E.SessionScoreCalculation,
        ///       E.LastUpdatedBy,
        ///       E.LastUpdatedTime,
        ///       E.CreatedTime,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evaluation_GetResultByEvaluationId {
            get {
                return ResourceManager.GetString("Evaluation_GetResultByEvaluationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @UserId INT
        ///SET @UserId = {0}
        ///DECLARE @EvaluationId INT
        ///SET @EvaluationId = {1}
        ///DECLARE @EvaluationType INT
        ///SET @EvaluationType = {2}
        ///
        ///IF @EvaluationType = 0   
        ///-- User
        ///     SELECT EP.EvaluationId,
        ///	   E.QuestionScoreCalculation,
        ///       ES.EvaluationSessionId,
        ///	   ET.UserId,
        ///	   EQ.EvaluationQuestionId,
        ///       ES.Label,
        ///       ES.EntryStartTime AS [Start],
        ///       ES.EntryCloseTime AS [End],
        ///       EQ.Name,
        ///       EQ.Question,
        ///       ER.Marks AS Result,
        ///	    CASE 
        ///            WHE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evaluation_GetResultDetail {
            get {
                return ResourceManager.GetString("Evaluation_GetResultDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(e.EvaluationId) AS TotalCount FROM Evaluations e WHERE e.IsDeleted = 0 AND e.CourseId = {0} AND e.[Name] LIKE N&apos;%{1}%&apos; .
        /// </summary>
        internal static string Evaluation_GetTotalCount {
            get {
                return ResourceManager.GetString("Evaluation_GetTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///	            DECLARE @IsGroup AS INT
        ///	            SET @IsGroup = {0}
        ///	            IF @IsGroup = 1 
        ///		            UPDATE EvaluationResponses SET IsDeleted = 1, LastUpdatedTime = GETUTCDATE() WHERE EvaluationId = {1} AND EvaluatorUserId = {2} AND TargetOrgUnitId IN ({3});
        ///	            ELSE
        ///		            UPDATE EvaluationResponses SET IsDeleted = 1, LastUpdatedTime = GETUTCDATE() WHERE EvaluationId = {1} AND EvaluatorUserId = {2} AND TargetUserId IN ({3});
        ///            END
        ///  .
        /// </summary>
        internal static string EvaluationResponse_ClearResponse {
            get {
                return ResourceManager.GetString("EvaluationResponse_ClearResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          BEGIN
        ///	          DECLARE @IsGroup AS INT
        ///	          SET @IsGroup = {0}
        ///	          IF @IsGroup = 1 
        ///		          UPDATE EvaluationResponses SET IsDeleted = 1, LastUpdatedTime = GETUTCDATE() WHERE EvaluationId = {1} AND TargetOrgUnitId = {2} AND EvaluatorUserId IN ({3});
        ///	          ELSE
        ///		          UPDATE EvaluationResponses SET IsDeleted = 1, LastUpdatedTime = GETUTCDATE() WHERE EvaluationId = {1} AND TargetUserId = {2} AND EvaluatorUserId IN ({3});
        ///          END
        ///    .
        /// </summary>
        internal static string EvaluationResponse_ClearResponseForTarget {
            get {
                return ResourceManager.GetString("EvaluationResponse_ClearResponseForTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [EvaluationResponseId]
        ///      ,[EvaluationId]
        ///      ,[EvaluationSessionId]
        ///      ,[EvaluationQuestionId]
        ///      ,[TargetUserId]
        ///      ,[TargetOrgUnitId]
        ///      ,[Marks]
        ///      ,[Comments]
        ///      ,[EvaluatorUserId]
        ///      ,[IsEvaluatorInstructor]
        ///      ,[LastUpdatedTime]
        ///      ,[IsDeleted]
        ///FROM [EvaluationResponses] 
        ///WHERE IsDeleted = 0 AND EvaluationSessionId = {0} AND EvaluatorUserId = {1}.
        /// </summary>
        internal static string EvaluationResponse_GetByEvaluationAndSession {
            get {
                return ResourceManager.GetString("EvaluationResponse_GetByEvaluationAndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	a.EvaluationResponseId,
        ///	a.EvaluationId,
        ///	a.EvaluationSessionId,
        ///	a.EvaluationQuestionId,
        ///	a.TargetUserId,
        ///	a.TargetOrgUnitId,
        ///	a.Marks,
        ///	a.Comments,
        ///	a.EvaluatorUserId,
        ///	a.IsEvaluatorInstructor,
        ///	a.LastUpdatedTime,
        ///	a.IsDeleted,
        ///	b.[Name] GroupName,
        ///	&apos;&apos; AS SectionName
        ///FROM 
        ///EvaluationResponses a  
        ///INNER JOIN CategoryGroups b ON b.Id = a.TargetOrgUnitId AND a.IsDeleted = 0 AND a.EvaluationId = {1}
        ///INNER JOIN CourseCategories c ON c.Id = b.CourseCategoryId
        ///INNER JOIN UserE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationResponse_GetByEvaluationIdWithTargetUnit {
            get {
                return ResourceManager.GetString("EvaluationResponse_GetByEvaluationIdWithTargetUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	a.EvaluationResponseId,
        ///	a.EvaluationId,
        ///	a.EvaluationSessionId,
        ///	a.EvaluationQuestionId,
        ///	a.TargetUserId,
        ///	a.TargetOrgUnitId,
        ///	a.Marks,
        ///	a.Comments,
        ///	a.EvaluatorUserId,
        ///	a.IsEvaluatorInstructor,
        ///	a.LastUpdatedTime,
        ///	a.IsDeleted,
        ///	b.DisplayName,
        ///	e.[Name] GroupName,
        ///	&apos;&apos; AS SectionName
        ///FROM 
        ///EvaluationResponses a
        ///INNER JOIN Users b ON a.TargetUserId = b.Id AND a.IsDeleted = 0
        ///INNER JOIN UserEnrollments c ON c.UserId = b.Id AND c.CourseId={0}
        ///INNER JOIN CourseCategories d  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationResponse_GetByEvaluationIdWithTargetUser {
            get {
                return ResourceManager.GetString("EvaluationResponse_GetByEvaluationIdWithTargetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT a.[EvaluationSessionId]
        ///      ,a.[EntryStartTime]
        ///      ,a.[EntryCloseTime]
        ///      ,a.[Weight]
        ///      ,a.[LastUpdatedBy]
        ///      ,a.[LastUpdatedTime]
        ///      ,a.[IsDeleted]
        ///      ,a.[Label]
        ///      ,a.[EvaluationId]
        ///  FROM [EvaluationSessions] a INNER JOIN EvaluationPairingSessions b ON b.EvaluationSessionId = a.EvaluationSessionId AND a.IsDeleted = 0
        ///  INNER JOIN EvaluationPairings c ON c.EvaluationPairingId = b.EvaluationPairingId AND c.EvaluationId =  {0}
        ///  ORDER BY a.EntryStartTime DE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetListByEvaluationId {
            get {
                return ResourceManager.GetString("EvaluationSession_GetListByEvaluationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///       us.Id AS UserId,
        ///       us.DisplayName,
        ///       us.EmailAddress,
        ///       us.OrgDefinedId,
        ///       cg.[Name] as GroupName, 
        ///       &apos;&apos; as SectionName,
        ///       ep.EvaluationPairingId
        ///FROM EvaluationPairingSessions eps 
        ///	INNER JOIN EvaluationPairings ep on eps.EvaluationPairingId = ep.EvaluationPairingId
        ///	INNER JOIN Evaluators evo ON ep.EvaluationPairingId = evo.EvaluationPairingId
        ///	INNER JOIN EvaluationTargets evt ON ep.EvaluationPairingId = evt.EvaluationPairingId
        ///	INNER JOIN Us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetMyEvaluationById {
            get {
                return ResourceManager.GetString("EvaluationSession_GetMyEvaluationById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///       us.Id AS UserId,
        ///       us.DisplayName,
        ///       us.EmailAddress,
        ///       us.OrgDefinedId,
        ///       cg.[Name] as GroupName, 
        ///       &apos;&apos; as SectionName,
        ///       ep.EvaluationPairingId
        ///FROM EvaluationPairingSessions eps 
        ///	INNER JOIN EvaluationPairings ep on eps.EvaluationPairingId = ep.EvaluationPairingId
        ///	INNER JOIN Evaluators evo ON ep.EvaluationPairingId = evo.EvaluationPairingId
        ///	INNER JOIN EvaluationTargets evt ON ep.EvaluationPairingId = evt.EvaluationPairingId
        ///	INNER JOIN Us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetMyEvaluationByIdWithInstructorRole {
            get {
                return ResourceManager.GetString("EvaluationSession_GetMyEvaluationByIdWithInstructorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	   es.[EvaluationSessionId]
        ///      ,es.[EntryStartTime]
        ///      ,es.[EntryCloseTime]
        ///      ,es.[Weight]
        ///      ,es.[LastUpdatedBy]
        ///      ,es.[LastUpdatedTime]
        ///      ,es.[IsDeleted]
        ///      ,es.[Label]
        ///	  ,e.EvaluationId
        ///	  ,e.[Name]
        ///FROM 
        ///	EvaluationSessions es 
        ///	INNER JOIN EvaluationPairingSessions eps ON eps.EvaluationSessionId = es.EvaluationSessionId
        ///	INNER JOIN EvaluationPairings ep ON ep.EvaluationId = es.EvaluationId
        ///	INNER JOIN Evaluations e ON e.EvaluationId = ep.Evaluatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetMyEvaluationSession {
            get {
                return ResourceManager.GetString("EvaluationSession_GetMyEvaluationSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	   es.[EvaluationSessionId]
        ///      ,es.[EntryStartTime]
        ///      ,es.[EntryCloseTime]
        ///      ,es.[Weight]
        ///      ,es.[LastUpdatedBy]
        ///      ,es.[LastUpdatedTime]
        ///      ,es.[IsDeleted]
        ///      ,es.[Label]
        ///	  ,e.EvaluationId
        ///	  ,e.[Name]
        ///    ,ep.EvaluationPairingId
        ///FROM 
        ///	EvaluationSessions es 
        ///	INNER JOIN EvaluationPairingSessions eps ON eps.EvaluationSessionId = es.EvaluationSessionId
        ///	INNER JOIN EvaluationPairings ep ON ep.EvaluationPairingId = eps.EvaluationPairingId AND ep.IsDelete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetMyEvaluationSessionByUser {
            get {
                return ResourceManager.GetString("EvaluationSession_GetMyEvaluationSessionByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	   es.[EvaluationSessionId]
        ///      ,es.[EntryStartTime]
        ///      ,es.[EntryCloseTime]
        ///      ,es.[Weight]
        ///      ,es.[LastUpdatedBy]
        ///      ,es.[LastUpdatedTime]
        ///      ,es.[IsDeleted]
        ///      ,es.[Label]
        ///	  ,e.EvaluationId
        ///	  ,e.[Name]
        ///    ,ep.EvaluationPairingId
        ///FROM 
        ///	EvaluationSessions es 
        ///	INNER JOIN EvaluationPairingSessions eps ON eps.EvaluationSessionId = es.EvaluationSessionId
        ///	INNER JOIN EvaluationPairings ep ON ep.EvaluationPairingId = eps.EvaluationPairingId AND ep.IsDelete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetMyEvaluationSessionByUserWithRole {
            get {
                return ResourceManager.GetString("EvaluationSession_GetMyEvaluationSessionByUserWithRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///       us.Id AS UserId,
        ///       us.DisplayName,
        ///       us.EmailAddress,
        ///       us.OrgDefinedId,
        ///       cg.[Name] as GroupName, 
        ///	   cg.Id AS GroupId,
        ///       &apos;&apos; as SectionName,
        ///       ep.EvaluationPairingId
        ///FROM EvaluationPairingSessions eps 
        ///	INNER JOIN EvaluationPairings ep on eps.EvaluationPairingId = ep.EvaluationPairingId  AND ep.IsDeleted = 0
        ///	INNER JOIN Evaluators evo ON ep.EvaluationPairingId = evo.EvaluationPairingId  AND evo.IsDeleted = 0
        ///	INNER JOIN EvaluationTargets evt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetStudentEvaluateOwnGroupEvaluationById {
            get {
                return ResourceManager.GetString("EvaluationSession_GetStudentEvaluateOwnGroupEvaluationById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///       us.Id as UserId,
        ///       us.DisplayName,
        ///       us.EmailAddress,
        ///       us.OrgDefinedId,
        ///	   cg.[Name] AS GroupName,
        ///	   cg.Id AS GroupId,
        ///	   &apos;&apos; AS SectionName
        ///FROM Users us     
        ///	INNER JOIN UserEnrollments ue ON us.Id = ue.UserId
        ///    INNER JOIN UserGroups ug ON ug.UserId = us.Id
        ///    INNER JOIN CategoryGroups cg ON cg.Id = ug.CategoryGroupId
        ///	INNER JOIN CourseCategories cc ON cc.Id = cg.CourseCategoryId AND cc.CourseId = {0}
        ///	INNER JOIN EvaluationTargets etg ON etg.OrgUni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetUserGroupSection {
            get {
                return ResourceManager.GetString("EvaluationSession_GetUserGroupSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///       us.Id AS UserId,
        ///       us.DisplayName,
        ///       us.EmailAddress,
        ///       us.OrgDefinedId,
        ///       cg.[Name] AS GroupName,
        ///       cg.Id AS GroupId,
        ///       &apos;&apos; AS SectionName,
        ///       etg.EvaluationPairingId
        ///FROM Users us
        ///    INNER JOIN UserEnrollments ue ON us.Id = ue.UserId
        ///    INNER JOIN UserGroups ug ON ug.UserId = us.Id
        ///    INNER JOIN CategoryGroups cg ON cg.Id = ug.CategoryGroupId
        ///    INNER JOIN CourseCategories cc ON cc.Id = cg.CourseCategoryId AND cc.CourseId = {0}
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetUserGroupSectionByUserId {
            get {
                return ResourceManager.GetString("EvaluationSession_GetUserGroupSectionByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///       us.Id AS UserId,
        ///       us.DisplayName,
        ///       us.EmailAddress,
        ///       us.OrgDefinedId,
        ///       cg.[Name] AS GroupName,
        ///       cg.Id AS GroupId,
        ///       &apos;&apos; AS SectionName,
        ///       etg.EvaluationPairingId
        ///FROM Users us
        ///    INNER JOIN UserEnrollments ue ON us.Id = ue.UserId
        ///    INNER JOIN UserGroups ug ON ug.UserId = us.Id
        ///    INNER JOIN CategoryGroups cg ON cg.Id = ug.CategoryGroupId
        ///    INNER JOIN CourseCategories cc ON cc.Id = cg.CourseCategoryId AND cc.CourseId = {0}
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluationSession_GetUserGroupSectionByUserIdWithRole {
            get {
                return ResourceManager.GetString("EvaluationSession_GetUserGroupSectionByUserIdWithRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE EvaluationPairingSessions WHERE EvaluationPairingId = {0}.
        /// </summary>
        internal static string EvaluationSessionParring_DeleteByEvaluationParringId {
            get {
                return ResourceManager.GetString("EvaluationSessionParring_DeleteByEvaluationParringId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO EvaluationPairingSessions (EvaluationPairingId,EvaluationSessionId ) VALUES ({0},{1}).
        /// </summary>
        internal static string EvaluationSessionParring_Insert {
            get {
                return ResourceManager.GetString("EvaluationSessionParring_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.[EvaluationTargetId]
        ///      ,e.[UserId]
        ///      ,e.[OrgUnitId]
        ///      ,e.[IsOrgUnit]
        ///      ,e.[IsDeleted]
        ///      ,e.[LastUpdatedBy]
        ///      ,e.[LastUpdatedTime]
        ///      ,e.[EvaluationPairingId]
        ///  FROM [EvaluationTargets] e INNER JOIN EvaluationPairings ep ON ep.EvaluationPairingId = e.EvaluationPairingId AND e.IsDeleted = 0 AND ep.EvaluationId = {0}.
        /// </summary>
        internal static string EvaluationTarget_GetListByEvaluationId {
            get {
                return ResourceManager.GetString("EvaluationTarget_GetListByEvaluationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.[EvaluatorId]
        ///      ,e.[UserId]
        ///      ,e.[OrgUnitId]
        ///      ,e.[IsOrgUnit]
        ///      ,e.[IsDeleted]
        ///      ,e.[LastUpdatedBy]
        ///      ,e.[LastUpdatedTime]
        ///      ,e.[EvaluationPairingId]
        ///  FROM [EvaluationTargets] e INNER JOIN EvaluationPairings ep ON ep.EvaluationPairingId = e.EvaluationPairingId AND e.IsDeleted = 0 AND e.IsOrgUnit = 1 AND e.OrgUnitId = {1} AND ep.EvaluationId = {0}.
        /// </summary>
        internal static string EvaluationTarget_GetListByEvaluationIdWithOrgUnit {
            get {
                return ResourceManager.GetString("EvaluationTarget_GetListByEvaluationIdWithOrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.[EvaluatorId]
        ///      ,e.[UserId]
        ///      ,e.[OrgUnitId]
        ///      ,e.[IsOrgUnit]
        ///      ,e.[IsDeleted]
        ///      ,e.[LastUpdatedBy]
        ///      ,e.[LastUpdatedTime]
        ///      ,e.[EvaluationPairingId]
        ///  FROM [EvaluationTargets] e INNER JOIN EvaluationPairings ep ON ep.EvaluationPairingId = e.EvaluationPairingId AND e.IsDeleted = 0 AND e.IsOrgUnit = 1 AND e.UserId = {1} AND ep.EvaluationId = {0}.
        /// </summary>
        internal static string EvaluationTarget_GetListByEvaluationIdWithUserId {
            get {
                return ResourceManager.GetString("EvaluationTarget_GetListByEvaluationIdWithUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT tg.OrgUnitId FROM EvaluationTargets tg INNER JOIN EvaluationPairings pair ON pair.EvaluationPairingId = tg.EvaluationPairingId AND tg.IsOrgUnit = 1 AND tg.IsDeleted = 0 AND pair.EvaluationId = {0} AND pair.IsDeleted = 0.
        /// </summary>
        internal static string EvaluationTarget_GetOrgUnitByEvaluationId {
            get {
                return ResourceManager.GetString("EvaluationTarget_GetOrgUnitByEvaluationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	tg.UserId, tg.OrgUnitId, us.OrgDefinedId, us.DisplayName AS [Name] 
        ///FROM 
        ///	EvaluationTargets tg 
        ///	INNER JOIN EvaluationPairings pair ON tg.EvaluationPairingId = pair.EvaluationPairingId AND tg.IsDeleted = 0 AND tg.IsOrgUnit = 0 AND pair.EvaluationId = {0} 
        ///	INNER JOIN Users us ON us.Id = tg.UserId 
        ///	INNER JOIN UserEnrollments ue ON ue.UserId = us.Id AND ue.RoleId IN ({1}).
        /// </summary>
        internal static string EvaluationTarget_GetUserDataByEvaluationIdAndRoleId {
            get {
                return ResourceManager.GetString("EvaluationTarget_GetUserDataByEvaluationIdAndRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Evaluator_GetDataInstruction {
            get {
                return ResourceManager.GetString("Evaluator_GetDataInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.[EvaluatorId]
        ///      ,e.[UserId]
        ///      ,e.[OrgUnitId]
        ///      ,e.[IsOrgUnit]
        ///      ,e.[IsDeleted]
        ///      ,e.[LastUpdatedBy]
        ///      ,e.[LastUpdatedTime]
        ///      ,e.[EvaluationPairingId]
        ///  FROM [Evaluators] e INNER JOIN EvaluationPairings ep ON ep.EvaluationPairingId = e.EvaluationPairingId AND e.IsDeleted = 0 AND ep.EvaluationId = {0}.
        /// </summary>
        internal static string Evaluator_GetListByEvaluationId {
            get {
                return ResourceManager.GetString("Evaluator_GetListByEvaluationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT tg.OrgUnitId FROM Evaluators tg INNER JOIN EvaluationPairings pair ON pair.EvaluationPairingId = tg.EvaluationPairingId AND tg.IsOrgUnit = 1 AND tg.IsDeleted = 0 AND pair.EvaluationId = {0} AND pair.IsDeleted = 0.
        /// </summary>
        internal static string Evaluator_GetOrgUnitByEvaluationId {
            get {
                return ResourceManager.GetString("Evaluator_GetOrgUnitByEvaluationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  BEGIN;
        ///    WITH tbl
        ///    AS (SELECT parring.EvaluationId,
        ///                NULL EvaluationResponseId,
        ///                etg.UserId,
        ///                NULL CourseId,
        ///                us.DisplayName,
        ///                cg.[Name] AS GroupName,
        ///                &apos;&apos; AS SectionName,
        ///			    us.OrgDefinedId
        ///        FROM Evaluators etg
        ///            INNER JOIN EvaluationPairings parring ON parring.EvaluationPairingId = etg.EvaluationPairingId
        ///            INNER JOIN Users us ON etg.UserId = us.Id AND etg.IsDeleted = 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evaluator_GetTotalCount {
            get {
                return ResourceManager.GetString("Evaluator_GetTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	tg.UserId, tg.OrgUnitId, us.OrgDefinedId, us.DisplayName AS [Name] 
        ///FROM 
        ///	Evaluators tg 
        ///	INNER JOIN EvaluationPairings pair ON tg.EvaluationPairingId = pair.EvaluationPairingId AND tg.IsDeleted = 0 AND tg.IsOrgUnit = 0 AND pair.EvaluationId = {0} 
        ///	INNER JOIN Users us ON us.Id = tg.UserId 
        ///	INNER JOIN UserEnrollments ue ON ue.UserId = us.Id AND ue.RoleId IN ({1}).
        /// </summary>
        internal static string Evaluator_GetUserDataByEvaluationIdAndRoleId {
            get {
                return ResourceManager.GetString("Evaluator_GetUserDataByEvaluationIdAndRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	el.UserId,
        ///	eps.EvaluationSessionId,
        ///	el.EvaluationPairingId
        ///	 FROM Evaluators el INNER JOIN EvaluationPairingSessions eps ON eps.EvaluationPairingId = el.EvaluationPairingId
        ///	 INNER JOIN  EvaluationSessions AS ES ON ES.EvaluationSessionId = eps.EvaluationSessionId AND ES.IsDeleted = 0
        ///	 INNER JOIN EvaluationPairings epr ON epr.EvaluationPairingId = eps.EvaluationPairingId AND epr.IsDeleted = 0
        ///	 INNER JOIN Evaluations ev ON ev.EvaluationId = epr.EvaluationId WHERE ev.EvaluationId = {0} AND  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evaluators_GetByEvaluationId {
            get {
                return ResourceManager.GetString("Evaluators_GetByEvaluationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT et.OrgUnitId,
        ///       et.UserId,
        ///       et.IsOrgUnit,
        ///       us.OrgDefinedId,
        ///       us.DisplayName,
        ///       &apos;&apos; AS Section
        ///FROM Evaluators et
        ///    INNER JOIN Users us
        ///        ON us.Id = et.UserId
        ///           AND et.EvaluationPairingId = {0};.
        /// </summary>
        internal static string Evaluators_GetEvaluatorsByPairingId {
            get {
                return ResourceManager.GetString("Evaluators_GetEvaluatorsByPairingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT et.OrgUnitId,
        ///       et.UserId,
        ///       et.IsOrgUnit,
        ///       us.OrgDefinedId,
        ///       us.DisplayName,
        ///       &apos;&apos; AS Section
        ///FROM Evaluators et
        ///    INNER JOIN Users us
        ///        ON us.Id = et.UserId
        ///           AND et.EvaluationPairingId = {0} AND et.UserId = {1} ;.
        /// </summary>
        internal static string Evaluators_GetEvaluatorsByPairingIdByEvaluatorUserId {
            get {
                return ResourceManager.GetString("Evaluators_GetEvaluatorsByPairingIdByEvaluatorUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT md.[Id]
        ///      ,md.[MarkRankLabelId]
        ///      ,md.[MarkNumber]
        ///      ,md.[Label]
        ///  FROM [MarkRankLabelDetail] md INNER JOIN MarkRankLabel ml ON md.MarkRankLabelId = ml.Id AND ml.IsDeleted = 0 AND ml.CourseId = {0}.
        /// </summary>
        internal static string RankMarkLabelDetail_GetByCourse {
            get {
                return ResourceManager.GetString("RankMarkLabelDetail_GetByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          BEGIN;
        ///              WITH tbl
        ///              AS (SELECT parring.EvaluationId,
        ///                         etg.UserId,
        ///                         etg.OrgUnitId,
        ///                         us.DisplayName,
        ///                         cg.[Name] AS GroupName,
        ///                         &apos;&apos; AS SectionName,
        ///			                  us.OrgDefinedId
        ///                  FROM Evaluators etg
        ///                      INNER JOIN EvaluationPairings parring ON parring.EvaluationPairingId = etg.EvaluationPairingId
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string User_GetEvaluationUserEntries {
            get {
                return ResourceManager.GetString("User_GetEvaluationUserEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          BEGIN;
        ///              WITH tbl
        ///              AS (SELECT parring.EvaluationId,
        ///                         etg.UserId,
        ///                         etg.OrgUnitId,
        ///                         us.DisplayName,
        ///                         cg.[Name] AS GroupName,
        ///                         &apos;&apos; AS SectionName,
        ///			                  us.OrgDefinedId
        ///                  FROM EvaluationTargets etg
        ///                      INNER JOIN EvaluationPairings parring ON parring.EvaluationPairingId = etg.EvaluationPairingId
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string User_GetEvaluationUserEntriesByTarget {
            get {
                return ResourceManager.GetString("User_GetEvaluationUserEntriesByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        /// b.UserId, d.Id AS OrgUnitId, a.OrgDefinedId, a.DisplayName AS &apos;Name&apos;
        ///FROM
        ///	Users a 
        ///	INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.CourseId = {0} AND b.RoleId IN ({1}) 
        ///	INNER JOIN CourseCategories c ON c.CourseId = b.CourseId 
        ///	INNER JOIN CategoryGroups d ON d.CourseCategoryId = c.Id AND d.Id IN ({2})
        ///	INNER JOIN UserGroups e ON e.CategoryGroupId = d.Id AND e.UserId = b.UserId.
        /// </summary>
        internal static string User_GetUserEnrollWithGroup {
            get {
                return ResourceManager.GetString("User_GetUserEnrollWithGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT cg.Id, ug.UserId FROM CategoryGroups cg 
        ///			INNER JOIN UserGroups ug ON ug.CategoryGroupId = cg.Id AND ug.UserId IN ({0})
        ///			INNER JOIN UserEnrollments ue ON ue.UserId = ug.UserId
        ///			INNER JOIN CourseCategories cc ON cc.Id = cg.CourseCategoryId AND cc.CourseId = {1}.
        /// </summary>
        internal static string User_GetUserWithCategoryGroup {
            get {
                return ResourceManager.GetString("User_GetUserWithCategoryGroup", resourceCulture);
            }
        }
    }
}
