//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnApps.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Grade {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Grade() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLearnApps.Data.Resources.Grade", typeof(Grade).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT GOB.Id, GOB.CategoryId AS CategoryId, GOB.Name, GradeType, GOB.Weight, GOB.MaxPoints, GOC.MaxPoints as CategoryMaxPoints, GOC.DisplayOrder as DisplayOrder
        ///      FROM GradeObject AS GOB
        ///      LEFT JOIN GradeObjectCategory AS GOC ON gob.CategoryId = GOC.Id 
        ///      WHERE GOB.CourseId = @CourseId
        ///      ORDER BY GOC.DisplayOrder
        ///    .
        /// </summary>
        internal static string Grade_GetByCourseId {
            get {
                return ResourceManager.GetString("Grade_GetByCourseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT gs.[GradeSubmissionId]
        ///      ,gs.[CourseId]
        ///      ,gs.[CourseOfferingCode]
        ///      ,gs.[SubmissionTime]
        ///      ,( SELECT DisplayName FROM dbo.Users WHERE id = gs.SubmittedBy ) SubmittedByName
        ///      ,gs.[IsLatest]
        ///	    ,Grs.RESET_STATUS
        ///      ,gs.AcknowledgeGradeRelease
        ///FROM [GradeSubmissions] gs INNER JOIN GradeResetStatus grs ON Grs.GradeSubmissionId = gs.GradeSubmissionId WHERE gs.CourseId = @CourseId.
        /// </summary>
        internal static string Grade_Submissions_GetByCourseId {
            get {
                return ResourceManager.GetString("Grade_Submissions_GetByCourseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT gs.[GradeSubmissionId]
        ///      ,gs.[CourseId]
        ///      ,gs.[CourseOfferingCode]
        ///      ,gs.[SubmissionTime]
        ///      ,( SELECT DisplayName FROM dbo.Users WHERE id = gs.SubmittedBy ) SubmittedByName
        ///      ,gs.[IsLatest]
        ///	    ,Grs.RESET_STATUS
        ///      ,gs.AcknowledgeGradeRelease
        ///      FROM [GradeSubmissions] gs INNER JOIN GradeResetStatus grs ON Grs.GradeSubmissionId = gs.GradeSubmissionId 
        ///      WHERE gs.CourseId IN @CourseIds.
        /// </summary>
        internal static string Grade_Submissions_GetByCourseIds {
            get {
                return ResourceManager.GetString("Grade_Submissions_GetByCourseIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    c.Id as CourseId,
        ///    COUNT(*) OVER() as TotalCount,
        ///	C.Name,
        ///    GS.CourseOfferingCode,
        ///    (SELECT TOP 1 Status from GPTReviewHistory where CourseId = C.ID ORDER BY ReviewedOn DESC) as ReviewStatus,
        ///	(SELECT TOP 1 ReviewedBy from GPTReviewHistory where CourseId = C.ID ORDER BY ReviewedOn DESC) as ReviewedBy,
        ///	(SELECT TOP 1 FlagReason from GPTReviewHistory where CourseId = C.ID ORDER BY ReviewedOn DESC) as FlagReason,
        ///    A.GradeSubmissionId,
        ///	B.TotalStudents,
        ///	GS.AcknowledgeGradeRelea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeDistribution_GetDistributionByCourseCodes {
            get {
                return ResourceManager.GetString("GradeDistribution_GetDistributionByCourseCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	   gm.[ModerationId]
        ///      ,gm.[CourseId]
        ///      ,gm.[GradeObjectId]
        ///      ,gm.[ModerationTypeId]
        ///      ,gm.[MarkRange1]
        ///      ,gm.[MarkRange2]
        ///      ,gm.[AdjustMarks]
        ///      ,gm.[LastUpdatedBy]
        ///      ,gm.[LastUpdatedTime]
        ///      ,gm.[IsDeleted]
        ///      ,gm.[DeletedBy]
        ///      ,gm.[DeletedTime]
        ///	  ,gmt.[Name] ModerationTypeName
        ///	  ,us.DisplayName AS ModeratedBy
        ///FROM 
        ///  [GradeModerations] gm
        ///  INNER JOIN dbo.GradeModerationTypes gmt ON gmt.ModerationTypeId = gm.ModerationTypeId
        ///  INNER JO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeModeration_GetByCourse {
            get {
                return ResourceManager.GetString("GradeModeration_GetByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	   gm.[ModerationId]
        ///      ,gm.[CourseId]
        ///      ,gm.[GradeObjectId]
        ///      ,gm.[ModerationTypeId]
        ///      ,gm.[MarkRange1]
        ///      ,gm.[MarkRange2]
        ///      ,gm.[AdjustMarks]
        ///      ,gm.[LastUpdatedBy]
        ///      ,gm.[LastUpdatedTime]
        ///      ,gm.[IsDeleted]
        ///      ,gm.[DeletedBy]
        ///      ,gm.[DeletedTime]
        ///	  ,gmt.[Name] ModerationTypeName
        ///	  ,us.DisplayName AS ModeratedBy
        ///FROM 
        ///  [GradeModerations] gm
        ///  INNER JOIN dbo.GradeModerationTypes gmt ON gmt.ModerationTypeId = gm.ModerationTypeId
        ///  INNER JO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeModeration_GetHistoryById {
            get {
                return ResourceManager.GetString("GradeModeration_GetHistoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [GradeModerations]
        ///           (
        ///           [CourseId]
        ///           ,[GradeObjectId]
        ///           ,[ModerationTypeId]
        ///           ,[MarkRange1]
        ///           ,[MarkRange2]
        ///           ,[AdjustMarks]
        ///           ,[LastUpdatedBy]
        ///           ,[LastUpdatedTime]
        ///           ,[IsDeleted]
        ///           ,[DeletedBy]
        ///           ,[DeletedTime])
        ///  OUTPUT Inserted.ModerationId    VALUES
        ///           (@CourseId
        ///           ,@GradeObjectId
        ///           ,@ModerationTypeId
        ///           ,@MarkRange1
        ///           ,@Mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeModeration_Insert {
            get {
                return ResourceManager.GetString("GradeModeration_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE GradeModerationMarks WHERE ModerationId = @ModerationId.
        /// </summary>
        internal static string GradeModerationMarks_Delete {
            get {
                return ResourceManager.GetString("GradeModerationMarks_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ModerationMarkId]
        ///      ,[ModerationId]
        ///      ,[UserId]
        ///      ,[GradeObjectId]
        ///      ,[MarksBefore]
        ///      ,[MarksAfter]
        ///      ,[MaxMarks]
        ///      ,[AdjustedMarksBefore]
        ///      ,[AdjustedMaxMarks]
        ///      ,[CalculatedMarksBefore]
        ///      ,[CalculatedMaxMarks]
        ///  FROM [GradeModerationMarks] WITH(NOLOCK) WHERE ModerationId = @ModerationId.
        /// </summary>
        internal static string GradeModerationMarks_GetByModerationId {
            get {
                return ResourceManager.GetString("GradeModerationMarks_GetByModerationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [GradeModerationMarks]
        ///           ([ModerationId]
        ///           ,[UserId]
        ///           ,[GradeObjectId]
        ///           ,[MarksBefore]
        ///           ,[MarksAfter]
        ///           ,[MaxMarks]
        ///           ,[AdjustedMarksBefore]
        ///           ,[AdjustedMaxMarks]
        ///           ,[CalculatedMarksBefore]
        ///           ,[CalculatedMaxMarks])
        ///     VALUES
        ///           (@ModerationId
        ///           ,@UserId
        ///           ,@GradeObjectId
        ///           ,@MarksBefore
        ///           ,@MarksAfter
        ///           ,@MaxMarks
        ///           ,@Adjus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeModerationMarks_Insert {
            get {
                return ResourceManager.GetString("GradeModerationMarks_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE GradeModerations SET IsDeleted = 1, DeletedBy = @DeletedBy, DeletedTime=@DeletedTime, LastUpdatedBy = @LastUpdatedBy, LastUpdatedTime = @LastUpdatedTime WHERE ModerationId = @ModerationId.
        /// </summary>
        internal static string GradeModerations_Delete {
            get {
                return ResourceManager.GetString("GradeModerations_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ModerationId]
        ///      ,[CourseId]
        ///      ,[GradeObjectId]
        ///      ,[ModerationTypeId]
        ///      ,[MarkRange1]
        ///      ,[MarkRange2]
        ///      ,[AdjustMarks]
        ///      ,[LastUpdatedBy]
        ///      ,[LastUpdatedTime]
        ///      ,[IsDeleted]
        ///      ,[DeletedBy]
        ///      ,[DeletedTime]
        ///  FROM [GradeModerations] WHERE ModerationId = @ModerationId AND IsDeleted = 0.
        /// </summary>
        internal static string GradeModerations_GetById {
            get {
                return ResourceManager.GetString("GradeModerations_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE GradeObject WHERE CourseId = @CourseId.
        /// </summary>
        internal static string GradeObject_Delete {
            get {
                return ResourceManager.GetString("GradeObject_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Name]
        ///      ,[ShortName]
        ///      ,[GradeType]
        ///      ,[CategoryId]
        ///      ,[DescriptionHtml]
        ///      ,[DescriptionText]
        ///      ,[Weight]
        ///      ,[ActivityId]
        ///      ,[MaxPoints]
        ///      ,[CanExceedMaxPoints]
        ///      ,[IsBonus]
        ///      ,[ExcludeFromFinalGradeCalculation]
        ///      ,[GradeSchemeId]
        ///      ,[GradeSchemeUrl]
        ///      ,[CourseId]
        ///  FROM [GradeObject] WHERE CourseId = @CourseId.
        /// </summary>
        internal static string GradeObject_GetByCourseId {
            get {
                return ResourceManager.GetString("GradeObject_GetByCourseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	c.UserId,
        ///	a.DisplayName,
        ///	d.[Name],
        ///	d.Id,
        ///	(CASE WHEN LOWER(d.GradeType) = &apos;text&apos; THEN -1 ELSE e.[Weight]  END) [Weight],
        ///	d.MaxPoints
        ///FROM 
        ///	dbo.Users a
        ///	INNER JOIN dbo.UserGradeObject b ON a.Id = b.UserId AND b.OrgUnitId = 6804
        ///	INNER JOIN dbo.UserEnrollments c ON a.Id = c.UserId AND c.CourseId = 6804
        ///	INNER JOIN dbo.GradeObject d ON d.Id = b.GradeObjectId
        ///	INNER JOIN dbo.GradeObjectCategory e ON e.Id = d.CategoryId.
        /// </summary>
        internal static string GradeObject_GetListData {
            get {
                return ResourceManager.GetString("GradeObject_GetListData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [GradeObject]
        ///           ([Id]
        ///           ,[Name]
        ///           ,[ShortName]
        ///           ,[GradeType]
        ///           ,[CategoryId]
        ///           ,[DescriptionHtml]
        ///           ,[DescriptionText]
        ///           ,[Weight]
        ///           ,[ActivityId]
        ///           ,[MaxPoints]
        ///           ,[CanExceedMaxPoints]
        ///           ,[IsBonus]
        ///           ,[ExcludeFromFinalGradeCalculation]
        ///           ,[GradeSchemeId]
        ///           ,[GradeSchemeUrl]
        ///           ,[CourseId]
        ///           ,[DisplayOrder])
        ///     VALUES
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeObject_Insert {
            get {
                return ResourceManager.GetString("GradeObject_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE dbo.GradeObjectCategory WHERE Id IN ( SELECT CategoryId FROM GradeObject WHERE CourseId = @CourseId ).
        /// </summary>
        internal static string GradeObjectCategory_Delete {
            get {
                return ResourceManager.GetString("GradeObjectCategory_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Name]
        ///      ,[ShortName]
        ///      ,[CanExceedMax]
        ///      ,[ExcludeFromFinalGrade]
        ///      ,[StartDate]
        ///      ,[EndDate]
        ///      ,[Weight]
        ///      ,[MaxPoints]
        ///      ,[AutoPoints]
        ///      ,[WeightDistributionType]
        ///      ,[NumberOfHighestToDrop]
        ///      ,[NumberOfLowestToDrop]
        ///  FROM [GradeObjectCategory] WHERE Id IN (SELECT CategoryId FROM dbo.GradeObject WHERE CourseId = @CourseId).
        /// </summary>
        internal static string GradeObjectCategory_GetByCourseId {
            get {
                return ResourceManager.GetString("GradeObjectCategory_GetByCourseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [GradeObjectCategory]
        ///           ([Id]
        ///           ,[Name]
        ///           ,[ShortName]
        ///           ,[CanExceedMax]
        ///           ,[ExcludeFromFinalGrade]
        ///           ,[StartDate]
        ///           ,[EndDate]
        ///           ,[Weight]
        ///           ,[MaxPoints]
        ///           ,[AutoPoints]
        ///           ,[WeightDistributionType]
        ///           ,[NumberOfHighestToDrop]
        ///           ,[NumberOfLowestToDrop]
        ///           ,[DisplayOrder])
        ///     VALUES
        ///           (@Id
        ///           ,@Name
        ///           ,@ShortName
        ///           ,@Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeObjectCategory_Insert {
            get {
                return ResourceManager.GetString("GradeObjectCategory_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT GR.GradeReleaseId,
        ///       GR.IsLatest,
        ///	   GRS.GradeReleaseSettingId,
        ///       GRS.GradeObjectId,
        ///       GRS.SortOrder,
        ///       GRS.IsReleased,
        ///       GRS.StartDate,
        ///       GRS.IsPointsDisplayed,
        ///       GRS.IsSymbolDisplayed,
        ///       GRS.IsWeightDisplayed,
        ///       GRS.IsAverageDisplayed,
        ///       GRS.IsMinMaxDisplayed,
        ///	   GR.LastUpdatedBy,
        ///	   U.DisplayName AS LastUpdatedUser,
        ///	   GR.LastUpdatedTime
        ///	    FROM GradeReleases GR
        ///INNER JOIN GradeReleaseSettings AS GRS ON GRS.GradeReleaseId = GR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeRelease_GetByOrgUnitId {
            get {
                return ResourceManager.GetString("GradeRelease_GetByOrgUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS(SELECT 1 FROM GradeReleases AS GR WHERE GR.OrgUnitId = @OrgUnitId)
        /// BEGIN
        ///
        /// UPDATE dbo.GradeReleases SET
        /// LastUpdatedBy = @LastUpdatedBy,
        /// LastUpdatedTime = @LastUpdatedTime
        /// OUTPUT Inserted.GradeReleaseId
        /// WHERE OrgUnitId = @OrgUnitId
        ///
        /// END
        /// ELSE
        /// BEGIN 
        ///
        ///INSERT INTO GradeReleases
        ///(
        ///    OrgUnitId,
        ///    LastUpdatedBy,
        ///    LastUpdatedTime,
        ///    IsLatest
        ///) OUTPUT Inserted.GradeReleaseId
        ///VALUES
        ///(   
        ///    @OrgUnitId,    
        ///    @LastUpdatedBy,      
        ///    @LastUpdatedTime, 
        ///    @IsLat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeRelease_Insert {
            get {
                return ResourceManager.GetString("GradeRelease_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO GradeReleaseSettings
        ///(
        ///    GradeReleaseId,
        ///    GradeObjectId,
        ///    OrgUnitId,
        ///    SortOrder,
        ///    IsReleased,
        ///    StartDate,
        ///    IsPointsDisplayed,
        ///    IsSymbolDisplayed,
        ///    IsWeightDisplayed,
        ///    IsAverageDisplayed,
        ///    IsMinMaxDisplayed
        ///)
        ///VALUES
        ///(
        ///   @GradeReleaseId,
        ///   @GradeObjectId,
        ///   @OrgUnitId,
        ///   @SortOrder,
        ///   @IsReleased,
        ///   @StartDate,
        ///   @IsPointsDisplayed,
        ///   @IsSymbolDisplayed,
        ///   @IsWeightDisplayed,
        ///   @IsAverageDisplayed,
        ///   @IsMinMaxDisplayed
        ///    ).
        /// </summary>
        internal static string GradeReleaseSetting_Insert {
            get {
                return ResourceManager.GetString("GradeReleaseSetting_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.GradeReleaseSettings SET
        ///    GradeReleaseId = @GradeReleaseId,
        ///    GradeObjectId = @GradeObjectId,
        ///    OrgUnitId = @OrgUnitId,
        ///    SortOrder = @SortOrder,
        ///    IsReleased = @IsReleased,
        ///    StartDate =  @StartDate,
        ///    IsPointsDisplayed = @IsPointsDisplayed,
        ///    IsSymbolDisplayed = @IsSymbolDisplayed,
        ///    IsWeightDisplayed = @IsWeightDisplayed,
        ///    IsAverageDisplayed = @IsAverageDisplayed,
        ///    IsMinMaxDisplayed = @IsMinMaxDisplayed
        ///WHERE GradeReleaseSettingId = @GradeReleaseSettingId.
        /// </summary>
        internal static string GradeReleaseSetting_Update {
            get {
                return ResourceManager.GetString("GradeReleaseSetting_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO GradeResetStatus
        ///(
        ///    GradeSubmissionId,
        ///    CourseId,
        ///    CourseOfferingCode,
        ///    ACAD_CAREER,
        ///    STRM,
        ///    CLASS_NBR,
        ///    RESET_STATUS,
        ///    SUBMISSION_DATE
        ///)
        ///VALUES
        ///(   @GradeSubmissionId,
        ///    @CourseId,
        ///    @CourseOfferingCode,
        ///    @ACAD_CAREER,
        ///    @STRM,
        ///    @CLASS_NBR,
        ///    @RESET_STATUS,
        ///    @SUBMISSION_DATE
        ///).
        /// </summary>
        internal static string GradeResetStatus_Insert {
            get {
                return ResourceManager.GetString("GradeResetStatus_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.GradeResetStatus SET
        ///    GradeSubmissionId = @GradeSubmissionId,
        ///    CourseId = @CourseId,
        ///    CourseOfferingCode = @CourseOfferingCode,
        ///    ACAD_CAREER = @ACAD_CAREER,
        ///    STRM = @STRM,
        ///    CLASS_NBR = @CLASS_NBR,
        ///    RESET_STATUS = @RESET_STATUS,
        ///    SUBMISSION_DATE = @SUBMISSION_DATE
        ///WHERE GradeSubmissionId = @GradeSubmissionId.
        /// </summary>
        internal static string GradeResetStatus_Update {
            get {
                return ResourceManager.GetString("GradeResetStatus_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1
        ///FROM Users a
        ///    INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.CourseId = @CourseId
        ///    INNER JOIN UserGradeObject c ON a.Id = c.UserId AND c.OrgUnitId = @CourseId AND c.GradeObjectTypeId IN (7, 8)
        ///	INNER JOIN GradeSubmissionGrades gg ON gg.GradeObjectId = c.GradeObjectId AND gg.CourseId = @CourseId AND gg.StudentId = c.UserId
        ///	INNER JOIN GradeSubmissions gs ON gs.GradeSubmissionId = gg.GradeSubmissionId
        ///	INNER JOIN GradeResetStatus gr ON gr.GradeSubmissionId = gs.Id AND gr.RESET_STAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradeSubmissionGrades_CheckExist {
            get {
                return ResourceManager.GetString("GradeSubmissionGrades_CheckExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT gsg.StudentId FROM 
        ///GradeSubmissions gs
        ///INNER JOIN GradeSubmissionGrades gsg ON gsg.CourseId = gs.CourseId AND gsg.CourseOfferingCode = gs.CourseOfferingCode AND gsg.GradeSubmissionId = gs.GradeSubmissionId
        ///INNER JOIN GradeResetStatus grs ON grs.GradeSubmissionId = gs.GradeSubmissionId AND grs.CourseId = gs.CourseId AND grs.RESET_STATUS = &apos;N&apos; WHERE gs.CourseId = @CourseId AND gs.CourseOfferingCode = @CourseOfferingCode.
        /// </summary>
        internal static string GradeSubmissionGrades_GetListStudentByCourseOfferingCode {
            get {
                return ResourceManager.GetString("GradeSubmissionGrades_GetListStudentByCourseOfferingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO GradeSubmissionGrades
        ///(
        ///    GradeSubmissionId,
        ///    StudentId,
        ///    GradeObjectId,
        ///    StudentOrgDefinedId,
        ///    OriginalFinalMarks,
        ///    FinalMarks,
        ///    FinalGrade,
        ///    CourseId,
        ///    CourseOfferingCode
        ///)
        ///VALUES
        ///(   @GradeSubmissionId,
        ///    @StudentId,
        ///    @GradeObjectId,
        ///    @StudentOrgDefinedId,
        ///    @OriginalFinalMarks,
        ///    @FinalMarks,
        ///    @FinalGrade,
        ///    @CourseId,
        ///    @CourseOfferingCode
        ///).
        /// </summary>
        internal static string GradeSubmissionGrades_Insert {
            get {
                return ResourceManager.GetString("GradeSubmissionGrades_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE GradeSubmissions SET IsLatest = &apos;0&apos; Where CourseOfferingCode = @CourseOfferingCode
        ///
        ///INSERT INTO GradeSubmissions
        ///(
        ///    CourseId,
        ///    CourseOfferingCode,
        ///    SubmissionTime,
        ///    SubmittedBy,
        ///    IsLatest,
        ///    AcknowledgeGradeRelease
        ///) OUTPUT INSERTED.GradeSubmissionId  
        ///VALUES
        ///(   @CourseId, 
        ///    @CourseOfferingCode,        
        ///    @SubmissionTime, 
        ///    @SubmittedBy,        
        ///	  @IsLatest,
        ///    @AcknowledgeGradeRelease
        ///).
        /// </summary>
        internal static string GradeSubmissions_Insert {
            get {
                return ResourceManager.GetString("GradeSubmissions_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [IGrades]
        ///           ([CourseOfferingCode]
        ///           ,[CourseId]
        ///           ,[SectionId]
        ///           ,[UserId]
        ///           ,[LastUpdatedBy]
        ///           ,[LastUpdatedTime])
        ///     VALUES
        ///           (@CourseOfferingCode
        ///           ,@CourseId
        ///           ,@SectionId
        ///           ,@UserId
        ///           ,@LastUpdatedBy
        ///           ,@LastUpdatedTime).
        /// </summary>
        internal static string IGrade_Insert {
            get {
                return ResourceManager.GetString("IGrade_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DELETE ig
        ///    FROM IGrades ig  WHERE ig.CourseOfferingCode = @CourseOfferingCode AND ig.SectionId = @SectionId AND ig.CourseId = @CourseId
        ///    AND NOT EXISTS
        ///    (
        ///        SELECT gsg.StudentId
        ///        FROM GradeSubmissions gs
        ///            INNER JOIN GradeSubmissionGrades gsg
        ///                ON gsg.CourseId = gs.CourseId
        ///                   AND gsg.CourseOfferingCode = gs.CourseOfferingCode
        ///                   AND gsg.GradeSubmissionId = gs.GradeSubmissionId
        ///            INNER JOIN GradeResetStatus gr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IGrades_Delete {
            get {
                return ResourceManager.GetString("IGrades_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	   [IGradeId]
        ///      ,[CourseOfferingCode]
        ///      ,[CourseId]
        ///      ,[SectionId]
        ///      ,[UserId]
        ///      ,[LastUpdatedBy]
        ///      ,[LastUpdatedTime]
        ///FROM IGrades ig
        ///WHERE ig.CourseId = @CourseId
        ///      AND ig.SectionId = @SectionId
        ///      AND NOT EXISTS
        ///          (
        ///              SELECT gsg.StudentId
        ///              FROM GradeSubmissionGrades gsg
        ///			        INNER JOIN GradeSubmissions gs ON gs.Id = gsg.GradeSubmissionId
        ///			        INNER JOIN GradeResetStatus grs ON grs.GradeSubmissionId = gs.Id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IGrades_GetByCourseAndSectionWithOutSubmit {
            get {
                return ResourceManager.GetString("IGrades_GetByCourseAndSectionWithOutSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ue.UserId,
        ///	ig.IGradeId,
        ///	se.SectionId,
        ///	se.[Name],
        ///	ig.LastUpdatedTime,
        ///	( SELECT u.DisplayName FROM Users u WHERE u.id = ig.LastUpdatedBy ) AS DisplayName
        ///FROM 
        ///	Users us
        ///    INNER JOIN UserEnrollments ue ON ue.UserId = us.Id AND ue.CourseId = @CourseId
        ///	INNER JOIN IGrades ig ON ig.UserId = us.Id AND ig.CourseId = ue.CourseId AND ig.SectionId = se.SectionId
        ///WHERE
        ///	 NOT EXISTS
        ///     (
        ///         SELECT gsg.StudentId
        ///         FROM GradeSubmissions gs
        ///             INNER JOIN Gra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IGrades_GetListAllByCourse {
            get {
                return ResourceManager.GetString("IGrades_GetListAllByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE UserGradeObject WHERE OrgUnitId = @CourseId AND UserId in @userIds.
        /// </summary>
        internal static string UserGradeObject_Delete {
            get {
                return ResourceManager.GetString("UserGradeObject_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.UserId,
        ///       a.DisplayName,
        ///       c.PointsNumerator,
        ///       c.DisplayedGrade,
        ///       c.GradeObjectId,
        ///       c.PointsDenominator,
        ///       c.OrgUnitCode,
        ///       c.OrgDefinedId,
        ///       c.WeightedDenominator,
        ///       c.WeightedNumerator,
        ///       c.Id,
        ///       c.GradeObjectTypeId
        ///    FROM Users a
        ///    INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.CourseId = @CourseId
        ///    INNER JOIN UserGradeObject c ON a.Id = c.UserId AND c.OrgUnitId = @CourseId AND c.GradeObjectTypeId IN (7, 8) AND [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGradeObject_GetByCourseAndSection {
            get {
                return ResourceManager.GetString("UserGradeObject_GetByCourseAndSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF @GradeObjectId &lt; 0
        ///                               BEGIN
        ///                               IF EXISTS (SELECT 1 FROM dbo.UserGradeObject AS UGO WHERE UGO.OrgUnitId = @CourseId AND UGO.GradeObjectTypeId = 8) 
        ///                               BEGIN
        ///                               SELECT TOP 1 @GradeObjectId = UGO.GradeObjectId FROM dbo.UserGradeObject AS UGO WHERE UGO.OrgUnitId = @CourseId AND UGO.GradeObjectTypeId = 8
        ///                               END
        ///                               ELSE
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGradeObject_GetByGradeObjectId {
            get {
                return ResourceManager.GetString("UserGradeObject_GetByGradeObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH cte
        ///AS (SELECT DISTINCT
        ///           c.UserId,
        ///           c.PointsNumerator,
        ///           c.DisplayedGrade,
        ///           c.GradeObjectId,
        ///           c.PointsDenominator,
        ///           c.OrgUnitCode,
        ///           c.OrgDefinedId,
        ///           c.WeightedDenominator,
        ///           c.WeightedNumerator,
        ///           c.GradeObjectTypeId,
        ///           COUNT(c.UserId) AS CountUser
        ///    FROM Users a
        ///        INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.CourseId = @CourseId
        ///        INNER JOIN UserGradeObject c  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGradeObject_GetDataForSubmitGrade {
            get {
                return ResourceManager.GetString("UserGradeObject_GetDataForSubmitGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	 a.DisplayName
        ///	,a.Id
        ///FROM Users a
        ///INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.CourseId = @CourseId
        ///INNER JOIN UserGradeObject c ON a.Id = c.UserId AND c.OrgUnitId = @CourseId
        ///INNER JOIN GradeObject d ON d.Id = c.GradeObjectId AND d.CourseId = @CourseId
        ///  .
        /// </summary>
        internal static string UserGradeObject_GetDisplayUser {
            get {
                return ResourceManager.GetString("UserGradeObject_GetDisplayUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 [Id]
        ///      ,[GradeObjectId]
        ///      ,[GradeObjectName]
        ///      ,[GradeObjectTypeId]
        ///      ,[GradeObjectTypeName]
        ///      ,[PointsNumerator]
        ///      ,[PointsDenominator]
        ///      ,[WeightedDenominator]
        ///      ,[WeightedNumerator]
        ///      ,[LastModifiedDate]
        ///      ,[GradeObjectStartDate]
        ///      ,[GradeObjectEndDate]
        ///      ,[CommentsForUser]
        ///      ,[GraderUserId]
        ///      ,[PrivateGradeComments]
        ///      ,[UserId]
        ///      ,[OrgUnitId]
        ///      ,[OrgUnitCode]
        ///      ,[DisplayedGrade]
        ///      ,[OrgDefinedId]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGradeObject_GetFirstItem {
            get {
                return ResourceManager.GetString("UserGradeObject_GetFirstItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	 ( SELECT u.DisplayName FROM Users u WHERE u.Id = ug.GraderUserId ) AS DisplayName,
        ///	ug.LastModifiedDate,
        ///  ug.UserId
        ///FROM 
        ///	Users us
        ///    INNER JOIN UserEnrollments ue ON ue.UserId = us.Id AND ue.CourseId = @CourseId
        ///    INNER JOIN UserGradeObject ug ON ug.UserId = us.Id AND LOWER(ug.DisplayedGrade) = &apos;i&apos; AND ug.GradeObjectTypeId IN (7,8) AND ug.OrgUnitId = @CourseId.
        /// </summary>
        internal static string UserGradeObject_GetGradeInfo {
            get {
                return ResourceManager.GetString("UserGradeObject_GetGradeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.UserId,
        ///       a.DisplayName,
        ///       c.PointsNumerator,
        ///       c.DisplayedGrade,
        ///       c.GradeObjectId,
        ///       c.PointsDenominator,
        ///       c.OrgUnitCode,
        ///       c.OrgDefinedId,
        ///       c.WeightedDenominator,
        ///       c.WeightedNumerator
        ///FROM Users a
        ///    INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.CourseId = @CourseId
        ///    INNER JOIN UserGradeObject c ON a.Id = c.UserId AND c.OrgUnitId = @CourseId AND c.GradeObjectTypeId IN (7, 8)
        ///    INNER JOIN GradeObject d ON d.Id = c.GradeObj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGradeObject_GetRoundedFinal {
            get {
                return ResourceManager.GetString("UserGradeObject_GetRoundedFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.UserId,
        ///       a.DisplayName,
        ///       c.PointsNumerator,
        ///       c.DisplayedGrade,
        ///       c.GradeObjectId,
        ///       c.PointsDenominator,
        ///       c.OrgUnitCode,
        ///       c.OrgDefinedId,
        ///       c.WeightedDenominator,
        ///       c.WeightedNumerator,
        ///       c.GradeObjectTypeId
        ///FROM Users a
        ///    INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.CourseId = @CourseId
        ///    INNER JOIN UserGradeObject c ON a.Id = c.UserId AND c.OrgUnitId = @CourseId AND c.GradeObjectTypeId IN (7, 8)
        ///	WHERE NOT EXISTS (        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGradeObject_GetStudentForIGrades {
            get {
                return ResourceManager.GetString("UserGradeObject_GetStudentForIGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	 a.DisplayName
        ///	,c.PointsNumerator
        ///	,c.PointsDenominator
        ///  ,c.WeightedDenominator
        ///  ,c.WeightedNumerator
        ///	,c.DisplayedGrade
        ///	,c.GradeObjectTypeId
        ///	,c.GradeObjectName
        ///	,c.GradeObjectId
        ///  ,d.CategoryId
        ///  ,c.UserId
        ///  ,c.GradeObjectTypeName
        ///  ,d.CourseId
        ///  ,e.MaxPoints As GradeObjectCategoryMaxPoints
        ///  ,c.CommentsForUser
        ///FROM Users a
        ///INNER JOIN UserEnrollments b ON a.Id = b.UserId AND b.CourseId = @CourseId
        ///INNER JOIN UserGradeObject c ON a.Id = c.UserId AND c.OrgUnitId = @CourseId
        ///I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGradeObject_GetUserGradeObjectByCourseId {
            get {
                return ResourceManager.GetString("UserGradeObject_GetUserGradeObjectByCourseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [UserGradeObject]
        ///           ([GradeObjectId]
        ///           ,[GradeObjectName]
        ///           ,[GradeObjectTypeId]
        ///           ,[GradeObjectTypeName]
        ///           ,[PointsNumerator]
        ///           ,[PointsDenominator]
        ///           ,[WeightedDenominator]
        ///           ,[WeightedNumerator]
        ///           ,[LastModifiedDate]
        ///           ,[GradeObjectStartDate]
        ///           ,[GradeObjectEndDate]
        ///           ,[CommentsForUser]
        ///           ,[GraderUserId]
        ///           ,[PrivateGradeComments]
        ///           ,[UserId]
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGradeObject_Insert {
            get {
                return ResourceManager.GetString("UserGradeObject_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE UserGradeObject SET DisplayedGrade = @DisplayedGrade, LastModifiedDate = @LastModifiedDate, GraderUserId = @GraderUserId WHERE UserId = @UserId AND GradeObjectId = @GradeObjectId.
        /// </summary>
        internal static string UserGradeObject_UpdateDisplayedGrade {
            get {
                return ResourceManager.GetString("UserGradeObject_UpdateDisplayedGrade", resourceCulture);
            }
        }
    }
}
