//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnApps.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLearnApps.Data.Resources.Ics", typeof(Ics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT [Id]
        ///        ,[SessionDate]
        ///        ,[StartTime]
        ///        ,[EndTime]
        ///        ,[CourseId]
        ///        ,[RecordStatus]
        ///        ,[CreatedOn]
        ///        ,[LastUpdatedOn]
        ///      FROM ICSSessions 
        ///      WHERE CourseId = @CourseId AND RecordStatus = 1 AND 
        ///            SessionDate = @SessionDate AND 
        ///            ((@StartTime &gt;= StartTime AND @StartTime &lt; EndTime) OR ( @EndTime &gt; StartTime AND @EndTime &lt;= EndTime ))
        ///    .
        /// </summary>
        internal static string ICCSSessions_CheckRange {
            get {
                return ResourceManager.GetString("ICCSSessions_CheckRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1
        ///FROM ICSSessions se
        ///WHERE EXISTS
        ///(
        ///    SELECT fb.ICSSessionId
        ///    FROM dbo.ICSSessionUserSenses fb
        ///    WHERE fb.ICSSessionId = se.Id
        ///          AND se.Id = 1
        ///)
        ///      OR EXISTS
        ///(
        ///    SELECT q.ICSSessionId
        ///    FROM dbo.Questions q
        ///    WHERE q.ICSSessionId = se.Id
        ///          AND se.Id = 1
        ///);.
        /// </summary>
        internal static string ICSSessions_CanDelete {
            get {
                return ResourceManager.GetString("ICSSessions_CanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[SessionDate]
        ///      ,[StartTime]
        ///      ,[EndTime]
        ///      ,[CourseId]
        ///      ,[RecordStatus]
        ///      ,[CreatedOn]
        ///      ,[LastUpdatedOn]
        ///      ,[Title]
        ///  FROM [ICSSessions] WHERE CourseId = @CourseId AND RecordStatus = 1.
        /// </summary>
        internal static string ICSSessions_GetByCourse {
            get {
                return ResourceManager.GetString("ICSSessions_GetByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[SessionDate]
        ///      ,[StartTime]
        ///      ,[EndTime]
        ///      ,[CourseId]
        ///      ,[RecordStatus]
        ///      ,[CreatedOn]
        ///      ,[LastUpdatedOn]
        ///  FROM [ICSSessions] WHERE RecordStatus = 1 AND Id = @Id.
        /// </summary>
        internal static string ICSSessions_GetById {
            get {
                return ResourceManager.GetString("ICSSessions_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE ICSSessionUserSenses WHERE ICSSessionId = @ICSSessionId AND UserId = @UserId;.
        /// </summary>
        internal static string ICSSessionUserSenses_DeleteByIdSessionIdUserId {
            get {
                return ResourceManager.GetString("ICSSessionUserSenses_DeleteByIdSessionIdUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[ICSSessionId]
        ///      ,[UserId]
        ///      ,[Sense]
        ///      ,[TimeStamp]
        ///  FROM [ICSSessionUserSenses] WHERE ICSSessionId IN @ids.
        /// </summary>
        internal static string ICSSessionUserSenses_GetListBySessionId {
            get {
                return ResourceManager.GetString("ICSSessionUserSenses_GetListBySessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ICSSessionUserSenses set Sense = @Sense WHERE ICSSessionId = @ICSSessionId.
        /// </summary>
        internal static string ICSSessionUserSenses_UpdateDoingWellBySessionId {
            get {
                return ResourceManager.GetString("ICSSessionUserSenses_UpdateDoingWellBySessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[LearningPointId]
        ///      ,[UserId]
        ///      ,[CreatedOn]
        ///  FROM [LearningPointChecks] WHERE LearningPointId IN @ids.
        /// </summary>
        internal static string LearningPointChecks_GetByListLearningPoint {
            get {
                return ResourceManager.GetString("LearningPointChecks_GetByListLearningPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Description]
        ///      ,[ICSSessionId]
        ///      ,[RecordStatus]
        ///      ,[CreatedOn]
        ///      ,[LastUpdatedOn]
        ///  FROM [LearningPoints] WHERE ICSSessionId IN @ids AND RecordStatus = 1.
        /// </summary>
        internal static string LearningPoints_GetByListSession {
            get {
                return ResourceManager.GetString("LearningPoints_GetByListSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Content]
        ///      ,[ICSSessionId]
        ///      ,[UserId]
        ///      ,[RecordStatus]
        ///      ,[CreatedOn]
        ///      ,[LastUpdatedOn]
        ///  FROM [Questions] WHERE ICSSessionId IN @ids AND RecordStatus = 1.
        /// </summary>
        internal static string Questions_GetByListSession {
            get {
                return ResourceManager.GetString("Questions_GetByListSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Questions SET Addressed=@Addressed, LastUpdatedOn=@LastUpdatedOn WHERE Id=@Id AND RecordStatus = 1;.
        /// </summary>
        internal static string Questions_UpdateAddressed {
            get {
                return ResourceManager.GetString("Questions_UpdateAddressed", resourceCulture);
            }
        }
    }
}
