//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnApps.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Journal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Journal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLearnApps.Data.Resources.Journal", typeof(Journal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        SELECT 
        ///             [Id]
        ///            ,[JournalId]
        ///            ,[UserId]
        ///            ,[Title]
        ///            ,[Body]
        ///            ,[IsDraft]
        ///            ,[IsRead]
        ///            ,[Status]
        ///            ,[LastUpdatedTime]
        ///            ,[LastUpdatedBy]
        ///        FROM [JournalEntries] WHERE JournalId = @JournalId AND UserId = @UserId AND [Status] = 1 AND IsDraft = 0
        ///    .
        /// </summary>
        internal static string Journal_GetEntryByStudent {
            get {
                return ResourceManager.GetString("Journal_GetEntryByStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        SELECT us.Id as UserId,
        ///          us.DisplayName,
        ///          us.OrgDefinedId,
        ///	        ( SELECT COUNT(DISTINCT je.JournalId) FROM JournalEntries je INNER JOIN Journals j ON j.Id = je.JournalId AND j.CourseId = @CourseId AND j.[Status]  &lt;&gt; 0 WHERE je.IsDraft = 0 AND je.[Status] = 1 AND je.UserId = us.Id  ) AS NumOfJournal
        ///        FROM Users us
        ///            INNER JOIN UserEnrollments ue ON us.Id = ue.UserId AND ue.CourseId = @CourseId
        ///	          INNER JOIN Roles rl ON rl.Id = ue.RoleId AND LOWER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journal_GetGroupByStudent {
            get {
                return ResourceManager.GetString("Journal_GetGroupByStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      SELECT DISTINCT j.[Id]
        ///          ,j.[CourseId]
        ///          ,j.[Title]
        ///          ,j.[Description]
        ///          ,j.[StartDate]
        ///          ,j.[EndDate]
        ///          ,( CASE
        ///            WHEN j.[Status] = 1 AND GETUTCDATE() &gt;= StartDate AND GETUTCDATE() &lt;= EndDate THEN 1
        ///            WHEN j.[Status] = 2 THEN 2
        ///            WHEN j.[Status] = 1 AND StartDate &gt; GETUTCDATE() THEN 3
        ///            ELSE 4
        ///              END
        ///              ) AS [JournalStatus]
        ///               ,j.[Status]
        ///          ,j.[LastUpdatedT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journal_GetJournalByStudent {
            get {
                return ResourceManager.GetString("Journal_GetJournalByStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        SELECT 
        ///             [Id]
        ///            ,[Title]
        ///        FROM [JournalEntries] WHERE JournalId = @JournalId AND UserId = @UserId AND [Status] = 1 AND IsDraft = 0
        ///    .
        /// </summary>
        internal static string Journal_GetListEntryBySuggest {
            get {
                return ResourceManager.GetString("Journal_GetListEntryBySuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        SELECT 
        ///	        COUNT(DISTINCT je.Id) CountNewEntry
        ///        FROM 
        ///	        Journals jn 
        ///	        INNER JOIN JournalEntries je ON jn.Id = je.JournalId
        ///          INNER JOIN UserEnrollments ue ON ue.UserId = je.UserId AND je.LastUpdatedBy = je.UserId 
        ///          INNER JOIN Roles rl ON rl.Id = ue.RoleId AND LOWER(rl.Name) = LOWER(@RoleName)
        ///        WHERE jn.CourseId = @CourseId AND jn.[Status]  &lt;&gt; 0 AND je.IsDraft = 0 AND je.IsRead = 0 AND je.[Status] = 1
        ///    .
        /// </summary>
        internal static string JournalEntries_GetCountNewEntry {
            get {
                return ResourceManager.GetString("JournalEntries_GetCountNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[JournalId]
        ///      ,[UserId]
        ///      ,[Title]
        ///      ,[Body]
        ///      ,[IsDraft]
        ///      ,[IsRead]
        ///      ,[Status]
        ///      ,[LastUpdatedTime]
        ///      ,[LastUpdatedBy]
        ///  FROM [JournalEntries] WHERE [Status] = 1 AND Id = @Id.
        /// </summary>
        internal static string JournalEntry_GetById {
            get {
                return ResourceManager.GetString("JournalEntry_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	   je.[Id]
        ///      ,je.[JournalId]
        ///      ,je.[UserId]
        ///      ,je.[Title]
        ///      ,je.[Body]
        ///      ,je.[IsDraft]
        ///      ,je.[IsRead]
        ///      ,je.[Status]
        ///      ,je.[LastUpdatedTime]
        ///      ,je.[LastUpdatedBy]
        ///	  ,( SELECT DisplayName FROM Users us WHERE us.Id = je.LastUpdatedBy ) AS LastUpdatedByName
        ///	  ,us.OrgDefinedId
        ///	  ,jec.Comment
        ///	  ,jec.LastUpdatedTime AS CommentUpdateTime
        ///	  ,jec.LastUpdatedBy AS CommentLastUpdateBy
        ///	  ,( SELECT DisplayName FROM Users us WHERE us.Id = jec.LastUpdatedB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEntry_GetEntryWithCommentByInstructor {
            get {
                return ResourceManager.GetString("JournalEntry_GetEntryWithCommentByInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	   je.[Id]
        ///      ,je.[JournalId]
        ///      ,je.[UserId]
        ///      ,je.[Title]
        ///      ,je.[Body]
        ///      ,je.[IsDraft]
        ///      ,je.[IsRead]
        ///      ,je.[Status]
        ///      ,je.[LastUpdatedTime]
        ///      ,je.[LastUpdatedBy]
        ///	  ,( SELECT DisplayName FROM Users us WHERE us.Id = je.LastUpdatedBy ) AS LastUpdatedByName
        ///	  ,us.OrgDefinedId
        ///	  ,jec.Comment
        ///	  ,jec.LastUpdatedTime AS CommentUpdateTime
        ///	  ,jec.LastUpdatedBy AS CommentLastUpdateBy
        ///	  ,( SELECT DisplayName FROM Users us WHERE us.Id = jec.LastUpdatedB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEntry_GetEntryWithCommentByUser {
            get {
                return ResourceManager.GetString("JournalEntry_GetEntryWithCommentByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT je.[Id]
        ///      ,je.[JournalId]
        ///      ,je.[UserId]
        ///	  ,( SELECT DisplayName FROM Users WHERE Id = je.[UserId] ) CreatedByName
        ///      ,je.[Title]
        ///      ,je.[Body]
        ///      ,je.[IsDraft]
        ///      ,je.[IsRead]
        ///      ,je.[Status]
        ///      ,je.[LastUpdatedTime]
        ///      ,je.[LastUpdatedBy]
        ///	  ,( SELECT DisplayName FROM Users WHERE Id = je.LastUpdatedBy ) LastUpdatedByName
        ///  FROM [JournalEntries] je INNER JOIN Journals j ON je.JournalId = j.Id AND j.CourseId = @CourseId WHERE je.[Status] = 1 AND je.UserId = @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEntry_GetListJournalEntry {
            get {
                return ResourceManager.GetString("JournalEntry_GetListJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        SELECT 
        ///	        je.Id,
        ///	        je.JournalId,
        ///	        je.Title,
        ///	        je.Body,
        ///	        us.DisplayName,
        ///	        us.OrgDefinedId,
        ///          je.UserId
        ///        FROM 
        ///	        JournalEntries je INNER JOIN Users us ON je.UserId = us.Id
        ///	        inner join Journals j ON j.Id = je.JournalId 
        ///        WHERE
        ///	        je.IsDraft = 0 AND je.[Status] = 1 AND j.[Status] = 1 AND  je.JournalId = @JournalId ORDER BY us.DisplayName
        ///    .
        /// </summary>
        internal static string JournalEntry_GetListJournalEntryStudent {
            get {
                return ResourceManager.GetString("JournalEntry_GetListJournalEntryStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(je.[Id]) FROM [JournalEntries] je INNER JOIN Journals j ON je.JournalId = j.Id AND j.CourseId = @CourseId WHERE je.[Status] = 1 AND je.UserId = @UserId.
        /// </summary>
        internal static string JournalEntry_GetTotalCount {
            get {
                return ResourceManager.GetString("JournalEntry_GetTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [JournalEntries]
        ///           ([JournalId]
        ///           ,[UserId]
        ///           ,[Title]
        ///           ,[Body]
        ///           ,[IsDraft]
        ///           ,[IsRead]
        ///           ,[Status]
        ///           ,[LastUpdatedTime]
        ///           ,[LastUpdatedBy]) OUTPUT INSERTED.ID
        ///     VALUES
        ///           (@JournalId
        ///           ,@UserId
        ///           ,@Title
        ///           ,@Body
        ///           ,@IsDraft
        ///           ,@IsRead
        ///           ,@Status
        ///           ,@LastUpdatedTime
        ///           ,@LastUpdatedBy).
        /// </summary>
        internal static string JournalEntry_Insert {
            get {
                return ResourceManager.GetString("JournalEntry_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [JournalEntries]
        ///   SET [JournalId] = @JournalId
        ///      ,[UserId] = @UserId
        ///      ,[Title] = @Title
        ///      ,[Body] = @Body
        ///      ,[IsDraft] = @IsDraft
        ///      ,[IsRead] = @IsRead
        ///      ,[Status] = @Status
        ///      ,[LastUpdatedTime] = @LastUpdatedTime
        ///      ,[LastUpdatedBy] = @LastUpdatedBy
        /// WHERE Id = @Id.
        /// </summary>
        internal static string JournalEntry_Update {
            get {
                return ResourceManager.GetString("JournalEntry_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE JournalEntries SET [IsRead] = @IsRead, LastUpdatedTime = @LastUpdatedTime, LastUpdatedBy = @LastUpdatedBy WHERE Id= @Id.
        /// </summary>
        internal static string JournalEntry_UpdateEntryByAnotherInstructor {
            get {
                return ResourceManager.GetString("JournalEntry_UpdateEntryByAnotherInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE JournalEntries SET IsRead = 1 WHERE Id = @Id.
        /// </summary>
        internal static string JournalEntry_UpdateIsRead {
            get {
                return ResourceManager.GetString("JournalEntry_UpdateIsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE JournalEntries SET [Status] = @Status, LastUpdatedTime = @LastUpdatedTime, LastUpdatedBy = @LastUpdatedBy WHERE Id= @Id.
        /// </summary>
        internal static string JournalEntry_UpdateStatus {
            get {
                return ResourceManager.GetString("JournalEntry_UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        BEGIN TRY
        ///          BEGIN TRANSACTION;
        ///		      --update entry
        ///		      UPDATE et
        ///		      SET et.[Status] = 0,
        ///			      et.LastUpdatedTime = @LastUpdatedTime,
        ///			      et.LastUpdatedBy = @LastUpdatedBy
        ///		      FROM JournalEntries et WHERE et.Id= @Id AND et.UserId = @UserId;
        ///		      -- update status entry comment
        ///		      UPDATE jec
        ///		      SET jec.[Status] = 0,
        ///			      jec.LastUpdatedTime = @LastUpdatedTime,
        ///			      jec.LastUpdatedBy = @LastUpdatedBy
        ///		      FROM JournalEntryComments j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEntry_UpdateStatusByStudent {
            get {
                return ResourceManager.GetString("JournalEntry_UpdateStatusByStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [JournalEntryComments] SET [Status] = 0 WHERE Id = @Id.
        /// </summary>
        internal static string JournalEntryComment_Delete {
            get {
                return ResourceManager.GetString("JournalEntryComment_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[JournalEntryId]
        ///      ,[UserId]
        ///      ,[Comment]
        ///      ,[IsRead]
        ///      ,[Status]
        ///      ,[LastUpdatedTime]
        ///      ,[LastUpdatedBy]
        ///  FROM [JournalEntryComments] WHERE Id = @Id AND [Status] = 1.
        /// </summary>
        internal static string JournalEntryComment_GetById {
            get {
                return ResourceManager.GetString("JournalEntryComment_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [JournalEntryComments]
        ///           ([JournalEntryId]
        ///           ,[UserId]
        ///           ,[Comment]
        ///           ,[IsRead]
        ///           ,[Status]
        ///           ,[LastUpdatedTime]
        ///           ,[LastUpdatedBy])  OUTPUT INSERTED.ID
        ///     VALUES
        ///           (@JournalEntryId
        ///           ,@UserId
        ///           ,@Comment
        ///           ,@IsRead
        ///           ,@Status
        ///           ,@LastUpdatedTime
        ///           ,@LastUpdatedBy).
        /// </summary>
        internal static string JournalEntryComment_Insert {
            get {
                return ResourceManager.GetString("JournalEntryComment_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE JournalEntryComments SET Comment = @Comment, LastUpdatedTime = @LastUpdatedTime, LastUpdatedBy=@LastUpdatedBy, IsRead = @IsRead WHERE Id = @Id.
        /// </summary>
        internal static string JournalEntryComment_UpdateComment {
            get {
                return ResourceManager.GetString("JournalEntryComment_UpdateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE JournalEntryComments SET IsRead = 1 WHERE JournalEntryId = @JournalEntryId.
        /// </summary>
        internal static string JournalEntryComment_UpdateIsRead {
            get {
                return ResourceManager.GetString("JournalEntryComment_UpdateIsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        SELECT [Id]
        ///            ,[JournalEntryId]
        ///            ,[UserId]
        ///            ,[Comment]
        ///            ,[IsRead]
        ///            ,[Status]
        ///            ,[LastUpdatedTime]
        ///            ,[LastUpdatedBy]
        ///        FROM [JournalEntryComments] WHERE JournalEntryId = @JournalEntryId AND [Status] = 1
        ///    .
        /// </summary>
        internal static string JournalEntryComments_GetByEntryId {
            get {
                return ResourceManager.GetString("JournalEntryComments_GetByEntryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          SELECT 
        ///            COUNT(DISTINCT jec.Id) NumOfUnread 
        ///          FROM 
        ///            JournalEntryComments jec 
        ///              INNER JOIN UserEnrollments ue ON ue.UserId = jec.LastUpdatedBy INNER JOIN Roles rl ON rl.Id = ue.RoleId AND LOWER(rl.Name) = LOWER(@RoleName)
        ///              INNER JOIN JournalEntries je ON je.Id = jec.JournalEntryId AND je.[Status] = 1
        ///			        INNER JOIN Journals j ON j.Id = je.JournalId AND j.CourseId = @CourseId AND j.[Status] = 1
        ///          WHERE 
        ///            je [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEntryComments_GetCountNewComment {
            get {
                return ResourceManager.GetString("JournalEntryComments_GetCountNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        SELECT 
        ///	        jec.Id,
        ///	        jec.Comment,
        ///	        jec.JournalEntryId,
        ///	        jec.LastUpdatedBy UserId,
        ///	        us.DisplayName
        ///        FROM 
        ///	        JournalEntries je 
        ///	        INNER JOIN Journals j ON j.Id = je.JournalId 
        ///	        INNER JOIN JournalEntryComments jec on jec.JournalEntryId = je.Id
        ///	        INNER JOIN Users us ON jec.LastUpdatedBy = us.Id
        ///        WHERE
        ///	        jec.[Status] = 1 AND je.IsDraft = 0 AND je.[Status] = 1 AND j.[Status] = 1 AND  je.JournalId = @Journa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JournalEntryComments_GetListJournalEntryCommentUser {
            get {
                return ResourceManager.GetString("JournalEntryComments_GetListJournalEntryCommentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Journals
        ///SET [Status] = 0,
        ///    LastUpdatedTime = @LastUpdatedTime,
        ///    LastUpdatedBy = @LastUpdatedBy
        ///WHERE Id IN @Ids;
        ///
        ///UPDATE et
        ///SET et.[Status] = 0,
        ///    et.LastUpdatedTime = @LastUpdatedTime,
        ///    et.LastUpdatedBy = @LastUpdatedBy
        ///FROM JournalEntries et
        ///    JOIN Journals j
        ///        ON et.JournalId = j.Id AND j.Id IN @Ids;
        ///UPDATE jec
        ///SET jec.[Status] = 0,
        ///    jec.LastUpdatedTime = @LastUpdatedTime,
        ///    jec.LastUpdatedBy = @LastUpdatedBy
        ///FROM JournalEntryComments jec
        ///    INNER JOIN J [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journals_Delete {
            get {
                return ResourceManager.GetString("Journals_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[CourseId]
        ///      ,[Title]
        ///      ,[Description]
        ///      ,[StartDate]
        ///      ,[EndDate]
        ///      ,(CASE
        ///            WHEN [Status] = 1 AND GETUTCDATE() &gt;= StartDate AND GETUTCDATE() &lt;= EndDate THEN 1 -- open
        ///            WHEN [Status] = 2 THEN 2 --locked
        ///            WHEN [Status] = 1 AND StartDate &gt; GETUTCDATE() THEN 3 --future
        ///            WHEN [Status] = 5 THEN 5 --private
        ///			      WHEN GETUTCDATE() &gt; EndDate THEN 4 --close
        ///        END
        ///       ) AS [Status]
        ///      ,[LastUpdatedTime]
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journals_GetByCourse {
            get {
                return ResourceManager.GetString("Journals_GetByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[CourseId]
        ///      ,[Title]
        ///      ,[Description]
        ///      ,[StartDate]
        ///      ,[EndDate]
        ///      ,[Status]
        ///       ,(CASE
        ///            WHEN [Status] = 1 AND GETUTCDATE() &gt;= StartDate AND GETUTCDATE() &lt;= EndDate THEN 1 -- open
        ///            WHEN [Status] = 2 THEN 2 --locked
        ///            WHEN [Status] = 1 AND StartDate &gt; GETUTCDATE() THEN 3 --future
        ///            WHEN [Status] = 5 THEN 5 --private
        ///			      WHEN GETUTCDATE() &gt; EndDate THEN 4 --close
        ///        END
        ///       ) AS [JournalStatus]
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journals_GetById {
            get {
                return ResourceManager.GetString("Journals_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[CourseId]
        ///      ,[Title]
        ///      ,[Description]
        ///      ,[StartDate]
        ///      ,[EndDate]
        ///      ,[Status]
        ///      ,[LastUpdatedTime]
        ///      ,[LastUpdatedBy]
        ///	  ,( SELECT COUNT(je.Id) FROM JournalEntries je WHERE je.JournalId = j.Id AND je.IsDraft = 0 AND je.IsRead = 0 AND je.Status = 1) AS NumOfUnreadEntry
        ///	  ,( SELECT COUNT(jec.Id) FROM JournalEntries je INNER JOIN JournalEntryComments jec ON je.Id = jec.JournalEntryId AND je.Status = 1 AND je.IsDraft = 0  AND jec.Status = 1 WHERE je.Jou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journals_GetJournalByCourse {
            get {
                return ResourceManager.GetString("Journals_GetJournalByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[CourseId]
        ///      ,[Title]
        ///      ,[Description]
        ///      ,[StartDate]
        ///      ,[EndDate]
        ///       ,(CASE
        ///            WHEN [Status] = 1 AND GETUTCDATE() &gt;= StartDate AND GETUTCDATE() &lt;= EndDate THEN 1
        ///            WHEN [Status] = 2 THEN 2
        ///            WHEN [Status] = 1 AND StartDate &gt; GETUTCDATE() THEN 3
        ///            ELSE 4
        ///        END
        ///       ) AS [Status]
        ///      ,[LastUpdatedTime]
        ///      ,[LastUpdatedBy]
        ///	    ,( SELECT COUNT(je.Id) FROM JournalEntries je WHERE je.[Status] = 1 AND je.Use [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journals_GetJournalByCourseAndUser {
            get {
                return ResourceManager.GetString("Journals_GetJournalByCourseAndUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///	IF @DisplayName IS NOT NULL AND LEN(@DisplayName) &gt; 0
        ///		SELECT us.[Id] as UserId,
        ///		   us.[DisplayName],
        ///		   us.[EmailAddress],
        ///		   us.[OrgDefinedId],
        ///		   us.[ProfileBadgeUrl],
        ///		   us.[ProfileIdentifier],
        ///		   ( SELECT COUNT(je.Id) FROM JournalEntries je WHERE je.UserId = us.Id AND je.[Status] = 1 AND je.IsDraft = 0  AND je.JournalId = @journalId ) AS NumOfEntry,
        ///		   ( SELECT COUNT(je.Id) FROM JournalEntries je WHERE je.UserId = us.Id AND je.[Status] = 1 AND je.IsDraft = 0  AND je.IsRea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journals_GetJournalStudentByCourse {
            get {
                return ResourceManager.GetString("Journals_GetJournalStudentByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(Id) FROM [Journals] WHERE CourseId = @CourseId AND [Status]  &lt;&gt; 0 .
        /// </summary>
        internal static string Journals_GetTotalCountByCourse {
            get {
                return ResourceManager.GetString("Journals_GetTotalCountByCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Journals]
        ///           ([CourseId]
        ///           ,[Title]
        ///           ,[Description]
        ///           ,[StartDate]
        ///           ,[EndDate]
        ///           ,[Status]
        ///           ,[LastUpdatedTime]
        ///           ,[LastUpdatedBy])
        ///     VALUES
        ///           (@CourseId
        ///           ,@Title
        ///           ,@Description
        ///           ,@StartDate
        ///           ,@EndDate
        ///           ,@Status
        ///           ,@LastUpdatedTime
        ///           ,@LastUpdatedBy).
        /// </summary>
        internal static string Journals_Insert {
            get {
                return ResourceManager.GetString("Journals_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///	IF @Id IS NOT NULL AND @Id &gt; 0
        ///		UPDATE [Journals]
        ///		   SET 
        ///			   [Title] = @Title
        ///			  ,[Description] = @Description
        ///			  ,[StartDate] = @StartDate
        ///			  ,[EndDate] = @EndDate
        ///			  ,[Status] = @Status
        ///			  ,[LastUpdatedTime] = @LastUpdatedTime
        ///			  ,[LastUpdatedBy] = @LastUpdatedBy
        ///		 WHERE Id = @Id
        ///	ELSE
        ///		INSERT INTO [Journals]
        ///           ([CourseId]
        ///           ,[Title]
        ///           ,[Description]
        ///           ,[StartDate]
        ///           ,[EndDate]
        ///           ,[Status]
        ///           ,[Las [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Journals_Save {
            get {
                return ResourceManager.GetString("Journals_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Journals]
        ///   SET 
        ///       [Title] = @Title
        ///      ,[Description] = @Description
        ///      ,[StartDate] = @StartDate
        ///      ,[EndDate] = @EndDate
        ///      ,[Status] = @Status
        ///      ,[LastUpdatedTime] = @LastUpdatedTime
        ///      ,[LastUpdatedBy] = @LastUpdatedBy
        /// WHERE Id = @Id.
        /// </summary>
        internal static string Journals_Update {
            get {
                return ResourceManager.GetString("Journals_Update", resourceCulture);
            }
        }
    }
}
