//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnApps.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lmsisis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lmsisis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLearnApps.Data.Resources.Lmsisis", typeof(Lmsisis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [CourseOfferingCode]
        ///      ,[ACAD_CAREER]
        ///      ,[STRM]
        ///      ,[CLASS_NBR]
        ///      ,[SIS_GRADE_TYPE]
        ///  FROM [PS_SIS_LMS_GRADE_TYPE] WHERE CourseOfferingCode = @CourseOfferingCode.
        /// </summary>
        internal static string PS_SIS_LMS_GRADE_TYPE_GetByCourseCode {
            get {
                return ResourceManager.GetString("PS_SIS_LMS_GRADE_TYPE_GetByCourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @ACADEMIC_YEAR NVARCHAR(10)
        ///DECLARE @ACADEMIC_TERM NVARCHAR(10)
        ///DECLARE @COURSE_ID NVARCHAR(10)
        ///
        ///SELECT @ACADEMIC_YEAR =
        ///       TCO.ACADEMIC_YEAR,
        ///      @ACADEMIC_TERM =  TCO.ACADEMIC_TERM,
        ///      @COURSE_ID = TCO.COURSE_ID FROM TL_CourseOfferings AS TCO WHERE TCO.CourseOfferingCode = @CourseOfferingCode
        ///
        ///SELECT DISTINCT TCO.CourseOfferingCode,
        ///       TCO.ACAD_CAREER,
        ///       TCO.STRM,
        ///       TCO.CLASS_NBR,
        ///       TCO.ACADEMIC_YEAR,
        ///       TCO.ACADEMIC_TERM,
        ///       TCO.COURSE_ID,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TL_CourseOfferingCode_GetByCourseCode {
            get {
                return ResourceManager.GetString("TL_CourseOfferingCode_GetByCourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT CourseOfferingCode FROM TL_CourseOfferings WHERE 1 = 1.
        /// </summary>
        internal static string TL_CourseOfferingCode_GetListCourseOfferingCodeByStrm {
            get {
                return ResourceManager.GetString("TL_CourseOfferingCode_GetListCourseOfferingCodeByStrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [CourseOfferingCode]
        ///      ,[ACAD_CAREER]
        ///      ,[STRM]
        ///      ,[CLASS_NBR]
        ///      ,[ACADEMIC_YEAR]
        ///      ,[ACADEMIC_TERM]
        ///      ,[COURSE_ID]
        ///      ,[SECTION_ID]
        ///      ,[MERGE_SECTION]
        ///      ,[START_DATE]
        ///      ,[END_DATE]
        ///      ,[INVALID]
        ///      ,[WORKSHOP]
        ///  FROM [TL_CourseOfferings] WHERE CourseOfferingCode = @CourseOfferingCode.
        /// </summary>
        internal static string TL_CourseOfferings_GetByCourseOfferingCode {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetByCourseOfferingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [CourseOfferingCode]
        ///      ,[ACAD_CAREER]
        ///      ,[STRM]
        ///      ,[CLASS_NBR]
        ///      ,[ACADEMIC_YEAR]
        ///      ,[ACADEMIC_TERM]
        ///      ,[COURSE_ID]
        ///      ,[SECTION_ID]
        ///      ,[MERGE_SECTION]
        ///      ,[START_DATE]
        ///      ,[END_DATE]
        ///      ,[INVALID]
        ///      ,[WORKSHOP]
        ///  FROM [TL_CourseOfferings] WHERE CourseOfferingCode IN (@list).
        /// </summary>
        internal static string TL_CourseOfferings_GetByListCourseOfferingCode {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetByListCourseOfferingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	DISTINCT co.STRM, co.ACADEMIC_YEAR, co.ACADEMIC_TERM
        ///FROM 
        ///	{0}Courses c
        ///	INNER JOIN {0}UserEnrollments ue on c.Id = ue.CourseId
        ///	INNER JOIN TL_CourseOfferings co on c.Code = co.CourseOfferingCode
        ///WHERE
        ///	LOWER(ACAD_CAREER)=LOWER(@ACAD_CAREER) AND co.MERGE_SECTION = 0 AND ((CONCAT(co.ACADEMIC_YEAR, &apos; T&apos;, co.ACADEMIC_TERM) like @filter) OR @filter = &apos;&apos;)
        ///ORDER BY ACADEMIC_YEAR DESC OFFSET @PageSize * (@PageNumber - 1) ROWS FETCH NEXT @PageSize ROWS ONLY;.
        /// </summary>
        internal static string TL_CourseOfferings_GetListByCodes {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetListByCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MERGE_SECTION FROM TL_CourseOfferings WHERE CourseOfferingCode = @CourseOfferingCode.
        /// </summary>
        internal static string TL_CourseOfferings_GetMergeSectionByCourseOfferingCode {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetMergeSectionByCourseOfferingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    ps.[CLASS_NBR] AS [CLASS_NBR], 
        ///    tl.[ACADEMIC_YEAR] AS [ACADEMIC_YEAR], 
        ///    ps.[ACAD_GROUP] AS [ACAD_GROUP], 
        ///    tl.[CourseOfferingCode] AS [CourseOfferingCode], 
        ///    ps.[STRM] AS [STRM], 
        ///    tl.[ACADEMIC_TERM] AS [ACADEMIC_TERM], 
        ///    ps.[CLASS_SECTION] AS [CLASS_SECTION]
        ///FROM  
        ///	[TL_CourseOfferings] AS tl INNER JOIN [PS_SIS_LMS_CLASS_V] AS ps ON tl.[STRM] = ps.[STRM]
        ///WHERE
        ///	CAST( ps.[CLASS_NBR] AS decimal(19,0)) = tl.[CLASS_NBR].
        /// </summary>
        internal static string TL_CourseOfferings_GetPeerFeedBackDashboard {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetPeerFeedBackDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    tl.[CLASS_NBR] AS [CLASS_NBR],
        ///    tl.[ACADEMIC_YEAR] AS [ACADEMIC_YEAR],
        ///    ps.[ACAD_GROUP] AS [ACAD_GROUP],
        ///    tl.[CourseOfferingCode] AS [CourseOfferingCode],
        ///    tl.[STRM] AS [STRM],
        ///    tl.[ACADEMIC_TERM] AS [ACADEMIC_TERM],
        ///    IIF(ps.[CLASS_SECTION] = null, tl.SECTION_ID, ps.[CLASS_SECTION]) AS [CLASS_SECTION]
        ///FROM
        ///    [TL_CourseOfferings] AS tl 
        ///    LEFT JOIN [PS_SIS_LMS_CLASS_V] AS ps ON tl.[STRM] = ps.[STRM]
        ///WHERE
        ///    CAST( ps.[CLASS_NBR] AS decimal(19,0)) = tl.[CLASS_NBR].
        /// </summary>
        internal static string TL_CourseOfferings_GetPeerFeedBackDownloadCSV {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetPeerFeedBackDownloadCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM (
        ///SELECT 
        ///	DISTINCT co.STRM, co.ACADEMIC_YEAR, co.ACADEMIC_TERM
        ///FROM 
        ///	{0}Courses c
        ///	INNER JOIN {0}UserEnrollments ue on c.Id = ue.CourseId
        ///	INNER JOIN TL_CourseOfferings co on c.Code = co.CourseOfferingCode 
        ///WHERE
        ///	LOWER(ACAD_CAREER)=LOWER (@ACAD_CAREER) AND co.MERGE_SECTION = 0 AND ((CONCAT(co.ACADEMIC_YEAR, &apos; T&apos;, co.ACADEMIC_TERM) like @filter) OR @filter = &apos;&apos;)) tbl;.
        /// </summary>
        internal static string TL_CourseOfferings_GetTotalCountByCodes {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetTotalCountByCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [CourseOfferingCode]
        ///      ,[SectionCode]
        ///      ,[SectionName]
        ///      ,[IndvCourseOfferingCode]
        ///  FROM [TL_MergeSections] WHERE CourseOfferingCode = @CourseOfferingCode .
        /// </summary>
        internal static string TL_MergeSections_GetByCourseCode {
            get {
                return ResourceManager.GetString("TL_MergeSections_GetByCourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [CourseOfferingCode]
        ///      ,[SectionCode]
        ///      ,[SectionName]
        ///      ,[IndvCourseOfferingCode]
        ///  FROM [TL_MergeSections] WHERE CourseOfferingCode = @CourseOfferingCode AND LOWER(SectionName) = LOWER(@SectionName);.
        /// </summary>
        internal static string TL_MergeSections_GetByCourseOfferingCode {
            get {
                return ResourceManager.GetString("TL_MergeSections_GetByCourseOfferingCode", resourceCulture);
            }
        }
    }
}
