//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnApps.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LmsTool {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LmsTool() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLearnApps.Data.Resources.LmsTool", typeof(LmsTool).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM AttendanceAttachments WHERE AttendanceAttachmentId = @AttendanceAttachmentId.
        /// </summary>
        internal static string AttendanceAttachment_DeleteAsync {
            get {
                return ResourceManager.GetString("AttendanceAttachment_DeleteAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM AttendanceAttachments WHERE AttendanceDataId = @AttendanceDataId.
        /// </summary>
        internal static string AttendanceAttachment_DeleteByAttendanceDataId {
            get {
                return ResourceManager.GetString("AttendanceAttachment_DeleteByAttendanceDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO AttendanceAttachments  OUTPUT INSERTED.AttendanceAttachmentId VALUES (@AttendanceDataId, @FileName, @AttachFile).
        /// </summary>
        internal static string AttendanceAttachment_Insert {
            get {
                return ResourceManager.GetString("AttendanceAttachment_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE AttendanceAttachments SET AttachFile = @AttachFile WHERE AttendanceAttachmentId = @AttendanceAttachmentId, [FileName] = @FileName
        ///  .
        /// </summary>
        internal static string AttendanceAttachment_Update {
            get {
                return ResourceManager.GetString("AttendanceAttachment_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	AttendanceDataId, AttendanceSessionId, UserId, [Percentage], Remarks, LastUpdatedBy, LastUpdatedTime, IsDeleted, Participation, Excused 
        ///FROM 
        ///	AttendanceDatas
        ///WHERE 
        ///	AttendanceSessionId = @AttendanceSessionId AND IsDeleted = 0 ORDER BY LastUpdatedTime, AttendanceDataId DESC;.
        /// </summary>
        internal static string AttendanceData_GetBySessionId {
            get {
                return ResourceManager.GetString("AttendanceData_GetBySessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [AttendanceDatas]
        ///           ([AttendanceSessionId]
        ///           ,[UserId]
        ///           ,[Percentage]
        ///           ,[Remarks]
        ///           ,[LastUpdatedBy]
        ///           ,[LastUpdatedTime]
        ///           ,[IsDeleted])
        ///     VALUES
        ///           (@AttendanceSessionId
        ///           ,@UserId
        ///           ,@Percentage
        ///           ,@Remarks
        ///           ,@LastUpdatedBy
        ///           ,@LastUpdatedTime
        ///           ,@IsDeleted).
        /// </summary>
        internal static string AttendanceData_Insert {
            get {
                return ResourceManager.GetString("AttendanceData_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///    DECLARE @DataId AS INT;
        ///    SET @DataId = 0;
        ///    SELECT @DataId = AttendanceDataId
        ///    FROM AttendanceDatas
        ///    WHERE AttendanceSessionId = @AttendanceSessionId
        ///          AND UserId = @UserId
        ///          AND IsDeleted = @IsDeleted
        ///    IF @AttendanceDataId &gt; 0
        ///        UPDATE [AttendanceDatas]
        ///        SET [AttendanceSessionId] = @AttendanceSessionId,
        ///            [UserId] = @UserId,
        ///            [Percentage] = @Percentage,
        ///            [LastUpdatedBy] = @LastUpdatedBy,
        ///            [LastUpda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceData_Save {
            get {
                return ResourceManager.GetString("AttendanceData_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [AttendanceDatas]
        ///SET 
        ///	 [Percentage] = @Percentage
        ///	,[Remarks] = @Remarks
        ///	,[LastUpdatedBy] = @LastUpdatedBy
        ///	,[LastUpdatedTime] = @LastUpdatedTime
        ///	,[Excused] = @Excused
        ///	,[Participation] = @Participation
        ///                  ,[IsDeleted] = @IsDeleted
        ///WHERE AttendanceDataId = @AttendanceDataId;.
        /// </summary>
        internal static string AttendanceData_Update {
            get {
                return ResourceManager.GetString("AttendanceData_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [AttendanceDatas]
        ///   SET [AttendanceSessionId] = {0}
        ///      ,[UserId] = @UserId
        ///      ,[Percentage] = @Percentage
        ///      ,[LastUpdatedBy] = {1}
        ///      ,[LastUpdatedTime] = GETUTCDATE()
        ///	  ,[IsDeleted] = 0
        /// WHERE AttendanceDataId = @AttendanceDataId.
        /// </summary>
        internal static string AttendanceData_UpdateAttendanceData {
            get {
                return ResourceManager.GetString("AttendanceData_UpdateAttendanceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE 
        ///	          [AttendanceDatas] 
        ///          SET 
        ///	          [LastUpdatedTime] = @LastUpdatedTime, [LastUpdatedBy] = @LastUpdatedBy, [Percentage] = @Percentage, Excused = @Excused
        ///          WHERE [AttendanceSessionId] = @AttendanceSessionId.
        /// </summary>
        internal static string AttendanceData_UpdateForSetAll {
            get {
                return ResourceManager.GetString("AttendanceData_UpdateForSetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [AttendanceDatas]
        ///   SET [AttendanceSessionId] = @AttendanceSessionId
        ///      ,[UserId] = @UserId
        ///      ,[Percentage] = @Percentage
        ///      ,[LastUpdatedBy] = @LastUpdatedBy
        ///      ,[LastUpdatedTime] = @LastUpdatedTime
        ///	  ,[IsDeleted] = @IsDeleted
        /// WHERE AttendanceDataId = @AttendanceDataId.
        /// </summary>
        internal static string AttendanceData_UpdatePercent {
            get {
                return ResourceManager.GetString("AttendanceData_UpdatePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Audit OUTPUT INSERTED.Id VALUES (@ToolId, @UserId, @OrgUnitId, @Type, @ResourceId, @TableName, @DateTime, @OldValues, @NewValues, @AffectedColumns, @PrimaryKeys);.
        /// </summary>
        internal static string Audit_Insert {
            get {
                return ResourceManager.GetString("Audit_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          SELECT 
        ///	          cg.Id AS CategoryId,
        ///	          cc.Id AS CourseCategoryId,
        ///	          cg.[Name],
        ///	          cc.[Name] AS CourseCategoryName,
        ///            cc.CourseId 
        ///          FROM 
        ///	          CategoryGroups cg 
        ///	          INNER JOIN CourseCategories cc ON cg.CourseCategoryId = cc.Id
        ///            INNER JOIN UserEnrollments ue ON ue.CourseId = cc.CourseId
        ///	          LEFT JOIN UserGroups ug ON cg.Id = ug.CategoryGroupId
        ///          WHERE
        ///	          cc.CourseId IN ({0})
        ///.
        /// </summary>
        internal static string CategoryGroup_GetListByMergeCourse {
            get {
                return ResourceManager.GetString("CategoryGroup_GetListByMergeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        WITH cte AS (
        ///	        SELECT
        ///		        NULL AS CategoryId,
        ///		        NULL AS [Name],
        ///		        cc.[Name] AS CourseCategoryName,
        ///		        cc.Id AS CourseCategoryId,
        ///            NULL NumOfStudent
        ///	        FROM
        ///		        CourseCategories cc
        ///		        INNER JOIN UserEnrollments ue ON ue.CourseId = cc.CourseId
        ///	        WHERE
        ///		        cc.CourseId = @CourseId
        ///	        UNION
        ///	        SELECT
        ///		        cg.Id AS CategoryId,
        ///		        cg.[Name],
        ///		        NULL AS CourseCategoryName,
        ///		     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CategoryGroup_GetListGroupByCourseCategoryId {
            get {
                return ResourceManager.GetString("CategoryGroup_GetListGroupByCourseCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///    DECLARE @PeerFeedBackPairingId AS INT
        ///    SET @PeerFeedBackPairingId = 0;
        ///    BEGIN TRANSACTION;
        ///
        ///    DECLARE @GroupIdInserted AS INT
        ///    DECLARE @UserId AS INT
        ///    DECLARE @GroupId AS INT
        ///   
        ///    SET @GroupIdInserted = 0;
        ///    DECLARE user_Cursor CURSOR FOR
        ///    SELECT 
        ///      DISTINCT u.Id AS UserId, ug.CategoryGroupId AS GroupId
        ///    FROM Users u
        ///        INNER JOIN UserGroups ug ON u.Id = ug.UserId
        ///        INNER JOIN CategoryGroups cg ON cg.id = ug.CategoryGroupId
        ///        INNER JOIN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PeerFeedBack_GeneratePairings {
            get {
                return ResourceManager.GetString("PeerFeedBack_GeneratePairings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PeerFeedbackEvaluators (UserId
        ///, OrgUnitId
        ///, IsOrgUnit
        ///, IsDeleted
        ///, LastUpdatedBy
        ///, LastUpdatedTime
        ///, PeerFeedbackPairingId)
        ///  VALUES (@UserId, @OrgUnitId, @IsOrgUnit, 0, @LastUpdatedBy, SYSUTCDATETIME(), @PeerFeedbackPairingId);.
        /// </summary>
        internal static string PeerFeedBackEvaluators_Insert {
            get {
                return ResourceManager.GetString("PeerFeedBackEvaluators_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PeerFeedbackPairings (PeerFeedbackId
        ///, LastUpdatedBy
        ///, LastUpdatedTime
        ///, IsDeleted) OUTPUT INSERTED.Id
        ///  VALUES (@PeerFeedbackId, @LastUpdatedBy, SYSDATETIME(), 0);.
        /// </summary>
        internal static string PeerFeedBackPairings_Insert {
            get {
                return ResourceManager.GetString("PeerFeedBackPairings_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PeerFeedBackPairingSessions (PeerFeedBackPairingId
        ///, PeerFeedBackSessionId)
        ///  VALUES (@PeerFeedBackPairingId, @PeerFeedBackSessionId);.
        /// </summary>
        internal static string PeerFeedBackPairingSessions_Insert {
            get {
                return ResourceManager.GetString("PeerFeedBackPairingSessions_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PeerFeedbackTargets (UserId
        ///, OrgUnitId
        ///, IsOrgUnit
        ///, IsDeleted
        ///, LastUpdatedBy
        ///, LastUpdatedTime
        ///, PeerFeedbackPairingId)
        ///  VALUES (@UserId, @OrgUnitId, @IsOrgUnit, 0, @LastUpdatedBy, SYSUTCDATETIME(), @PeerFeedbackPairingId);.
        /// </summary>
        internal static string PeerFeedBackTargets_Insert {
            get {
                return ResourceManager.GetString("PeerFeedBackTargets_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	DISTINCT co.STRM, co.ACADEMIC_YEAR, co.ACADEMIC_TERM
        ///FROM 
        ///	Courses c
        ///	INNER JOIN UserEnrollments ue on c.Id = ue.CourseId
        ///	INNER JOIN {0}TL_CourseOfferings co on c.Code = co.CourseOfferingCode
        ///WHERE
        ///	co.MERGE_SECTION = 0 AND ((CONCAT(co.ACADEMIC_YEAR, &apos; T&apos;, co.ACADEMIC_TERM) like @filter) OR @filter = &apos;&apos;) {1}
        ///ORDER BY ACADEMIC_YEAR DESC;.
        /// </summary>
        internal static string TL_CourseOfferings_GetListByCodes {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetListByCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM (
        ///SELECT 
        ///	DISTINCT co.STRM, co.ACADEMIC_YEAR, co.ACADEMIC_TERM
        ///FROM 
        ///	Courses c
        ///	INNER JOIN UserEnrollments ue on c.Id = ue.CourseId
        ///	INNER JOIN {0}TL_CourseOfferings co on c.Code = co.CourseOfferingCode 
        ///WHERE
        ///	co.MERGE_SECTION = 0 AND ((CONCAT(co.ACADEMIC_YEAR, &apos; T&apos;, co.ACADEMIC_TERM) like @filter) OR @filter = &apos;&apos;) {1}) tbl;.
        /// </summary>
        internal static string TL_CourseOfferings_GetTotalCountByCodes {
            get {
                return ResourceManager.GetString("TL_CourseOfferings_GetTotalCountByCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///  ug.UserId, ug.CategoryGroupId 
        ///FROM 
        ///  CategoryGroups cg 
        ///  INNER JOIN CourseCategories cc ON cg.CourseCategoryId = cc.Id
        ///  INNER JOIN UserGroups ug ON ug.CategoryGroupId = cg.Id
        ///  INNER JOIN Users u ON u.Id = ug.UserId
        ///  INNER JOIN Courses c ON c.Id = cc.CourseId
        ///WHERE 
        ///  c.Code IN @courseOfferingCodes.
        /// </summary>
        internal static string UserGroup_GetPeerFeedBackTargetUser {
            get {
                return ResourceManager.GetString("UserGroup_GetPeerFeedBackTargetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM UserUploadFiles WHERE UserId = @UserId AND Id = @Id;.
        /// </summary>
        internal static string UserUploadFile_DeleteByUserIdAndId {
            get {
                return ResourceManager.GetString("UserUploadFile_DeleteByUserIdAndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, UserId, FileBlob, FileMeta, Filename, Category FROM UserUploadFiles WHERE UserId = @UserId AND Category = @Category;.
        /// </summary>
        internal static string UserUploadFile_GetByUserId {
            get {
                return ResourceManager.GetString("UserUploadFile_GetByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, UserId, FileBlob, FileMeta, Filename, Category FROM UserUploadFiles WHERE UserId = @UserId AND Id = @Id;.
        /// </summary>
        internal static string UserUploadFile_GetByUserIdAndId {
            get {
                return ResourceManager.GetString("UserUploadFile_GetByUserIdAndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO UserUploadFiles OUTPUT INSERTED.Id VALUES (@UserId, @FileBlob, @FileMeta, @Filename, @Category);.
        /// </summary>
        internal static string UserUploadFile_Insert {
            get {
                return ResourceManager.GetString("UserUploadFile_Insert", resourceCulture);
            }
        }
    }
}
