//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnApps.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logging() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLearnApps.Data.Resources.Logging", typeof(Logging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [AuditLogs] ([UserId] ,[ToolId] ,[OrgUnitId] ,[ToolAccessRoleId] ,[ActionCategory] ,[ActionDescription] ,[ActionTime] ,[IpAddress] ,[SessionId]) VALUES (@UserId ,@ToolId ,@OrgUnitId ,@ToolAccessRoleId ,@ActionCategory ,@ActionDescription ,@ActionTime ,@IpAddress ,@SessionId).
        /// </summary>
        internal static string AuditLog_Insert {
            get {
                return ResourceManager.GetString("AuditLog_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [BatchJobLogDetails]
        ///           ([BatchJobLogId]
        ///           ,[LogLevel]
        ///           ,[LogContent]
        ///           ,[CreatedOn])
        ///     VALUES
        ///           (@BatchJobLogId
        ///           ,@LogLevel
        ///           ,@LogContent
        ///           ,@CreatedOn ).
        /// </summary>
        internal static string BatchJobLogDetails_Insert {
            get {
                return ResourceManager.GetString("BatchJobLogDetails_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [BatchJobLogs] ([ExecutableName] ,[Parameters] ,[JobStart] ,[JobEnd] ,[CreatedOn] ,[LastUpdatedOn]) OUTPUT Inserted.Id VALUES (@ExecutableName ,@Parameters ,@JobStart ,@JobEnd ,@CreatedOn ,@LastUpdatedOn).
        /// </summary>
        internal static string BatchJobLogs_Insert {
            get {
                return ResourceManager.GetString("BatchJobLogs_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS DebugLog(
        ///	Id integer primary key AUTOINCREMENT,
        ///	ShortMessage text,
        ///	FullMessage  text,
        ///	IpAddress  VARCHAR(20),
        ///	PageUrl  text,
        ///	ReferrerUrl  text,
        ///	UserId INTEGER,
        ///	OrgUnitId INTEGER,
        ///	SessionId  VARCHAR(50),
        ///	ToolId  VARCHAR(20),
        ///	Browser  VARCHAR(50),
        ///	QueryString  text,
        ///	RequestBody  text,
        ///	CreateOn TEXT
        ///).
        /// </summary>
        internal static string DebugLog_CreateTableIfNotExists {
            get {
                return ResourceManager.GetString("DebugLog_CreateTableIfNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO DebugLog(ShortMessage, FullMessage, IpAddress, PageUrl, ReferrerUrl, UserId, OrgUnitId, SessionId, ToolId, Browser, QueryString, RequestBody, CreateOn) VALUES (@ShortMessage, @FullMessage, @IpAddress, @PageUrl, @ReferrerUrl, @UserId, @OrgUnitId, @SessionId, @ToolId, @Browser, @QueryString, @RequestBody, @CreateOn);.
        /// </summary>
        internal static string DebugLog_Insert {
            get {
                return ResourceManager.GetString("DebugLog_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [ErrorLogs]
        ///           ([UserId]
        ///           ,[ToolId]
        ///           ,[OrgUnitId]
        ///           ,[ToolAccessRoleId]
        ///           ,[ErrorPage]
        ///           ,[ErrorMessage]
        ///           ,[ErrorDetails]
        ///           ,[ErrorTime]
        ///           ,[IpAddress]
        ///           ,[SessionId])
        ///     VALUES
        ///           (@UserId
        ///           ,@ToolId
        ///           ,@OrgUnitId
        ///           ,@ToolAccessRoleId
        ///           ,@ErrorPage
        ///           ,@ErrorMessage
        ///           ,@ErrorDetails
        ///           ,@ErrorTime
        ///           ,@IpAd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorLogs_Insert {
            get {
                return ResourceManager.GetString("ErrorLogs_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [GPTAuditLogs] 
        ///            ([Action] ,[ActionByUserId] ,[ActionByName], [CourseId], [CourseName], [ActionTime], [IpAddress], [SessionId])  
        ///    VALUES 
        ///            (@Action ,@ActionByUserId ,@ActionByName, @CourseId, @CourseName, @ActionTime, @IpAddress, @SessionId)
        ///    .
        /// </summary>
        internal static string GPTAuditLog_Insert {
            get {
                return ResourceManager.GetString("GPTAuditLog_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [GPTDebugLogs] ([Description] ,[CreatedOn] ,[SessionId])  VALUES (@Description ,@CreatedOn ,@SessionId)
        ///    .
        /// </summary>
        internal static string GPTDebugLog_Insert {
            get {
                return ResourceManager.GetString("GPTDebugLog_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [ToolAccessLogs]
        ///           ([ToolId ]
        ///           ,[UserId]
        ///           ,[Username]
        ///           ,[AccessTime]
        ///           ,[IpAddress]
        ///           ,[OrgUnitId]
        ///           ,[OrgUnitRoleId]
        ///           ,[SessionId])
        ///     VALUES
        ///           (@ToolId
        ///           ,@UserId
        ///           ,@Username
        ///           ,@AccessTime
        ///           ,@IpAddress
        ///           ,@OrgUnitId
        ///           ,@OrgUnitRoleId
        ///           ,@SessionId).
        /// </summary>
        internal static string ToolAccessLogs_Insert {
            get {
                return ResourceManager.GetString("ToolAccessLogs_Insert", resourceCulture);
            }
        }
    }
}
