//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnApps.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLearnApps.Data.Resources.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS #WhitelistedCourseCodeAcademicGroup
        ///SELECT Courses.Id AS CourseId,
        ///		Courses.Code AS CourseCode,
        ///		PS_SIS_LMS_CLASS_V.ACAD_GROUP AS AcadGroup,
        ///		STUFF((SELECT &apos;; &apos; + Users.DisplayName
        ///		FROM UserEnrollments
        ///		INNER JOIN Users
        ///			ON Users.Id = UserEnrollments.UserId
        ///		WHERE UserEnrollments.CourseId = Courses.Id
        ///			AND UserEnrollments.RoleId = 106
        ///		ORDER BY Users.DisplayName
        ///		FOR XML PATH(&apos;&apos;)), 1, 1, &apos;&apos;) AS Instructor
        ///INTO #WhitelistedCourseCodeAcademicGroup
        ///FROM Courses
        ///L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string descriptor_response_by_coursecode {
            get {
                return ResourceManager.GetString("descriptor_response_by_coursecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DROP TABLE #WhitelistedCourses
        ///--DROP TABLE #Temp_Users
        ///--DROP TABLE #QueryFilters
        ///--DROP TABLE #TotalTargetsPerSchoolCodeAcademicYear
        ///--DROP TABLE #Temp_Responses
        ///--DROP TABLE #Temp_DescriptorResponse
        ///
        ///--DROP TABLE IF EXISTS #WhitelistedCourses
        ///--DROP TABLE IF EXISTS #Temp_Users
        ///--DROP TABLE IF EXISTS #QueryFilters
        ///--DROP TABLE IF EXISTS #TotalTargetsPerSchoolCodeAcademicYear
        ///--DROP TABLE IF EXISTS #Temp_Responses
        ///--DROP TABLE IF EXISTS #Temp_DescriptorResponse
        ///
        ///IF OBJECT_ID(&apos;tempdb.dbo.#Wh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string descriptor_response_by_studentschool_intakeyear {
            get {
                return ResourceManager.GetString("descriptor_response_by_studentschool_intakeyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;tempdb.dbo.#Temp_GroupReadiness_Base&apos;, &apos;U&apos;) IS NOT NULL
        ///	DROP TABLE #Temp_GroupReadiness_Base
        ///SELECT	Org_Units.OrgUnitId OrgUnitId,
        ///		Org_Units.Code CourseCode, 
        ///		Org_Units.Name CourseName, 
        ///		
        ///		STUFF((SELECT &apos;] [&apos; + Users.FirstName + &apos; - &apos; + Users.ExternalEmail
        ///				FROM User_Enrollments
        ///				INNER JOIN Users
        ///					ON Users.UserId = User_Enrollments.UserId
        ///				WHERE User_Enrollments.OrgUnitId = Org_Units.OrgUnitId
        ///					AND User_Enrollments.RoleId = 106
        ///				ORDER BY Users.FirstName        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string group_readiness {
            get {
                return ResourceManager.GetString("group_readiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DROP TABLE IF EXISTS #WhitelistedCourseCodeAcademicGroup
        ///IF OBJECT_ID(&apos;tempdb.dbo.#WhitelistedCourseCodeAcademicGroup&apos;, &apos;U&apos;) IS NOT NULL
        ///	DROP TABLE #WhitelistedCourseCodeAcademicGroup; 
        ///SELECT Courses.Id AS CourseId,
        ///		Courses.Code AS CourseCode,
        ///		PS_SIS_LMS_CLASS_V.ACAD_GROUP AS AcadGroup,
        ///		STUFF((SELECT &apos;; &apos; + Users.DisplayName
        ///		FROM UserEnrollments
        ///		INNER JOIN Users
        ///			ON Users.Id = UserEnrollments.UserId
        ///		WHERE UserEnrollments.CourseId = Courses.Id
        ///			AND UserEnrollments.RoleId = 106        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mean_score_by_coursecode {
            get {
                return ResourceManager.GetString("mean_score_by_coursecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DROP TABLE IF EXISTS #WhitelistedCourses
        ///--DROP TABLE IF EXISTS #Temp_Responses
        ///--DROP TABLE IF EXISTS #Temp_Question1
        ///--DROP TABLE IF EXISTS #Temp_Question2
        ///--DROP TABLE IF EXISTS #Temp_Question3
        ///--DROP TABLE IF EXISTS #MedianResponseRate
        ///--DROP TABLE IF EXISTS #CTE_RC1
        ///--DROP TABLE IF EXISTS #CTE_CE1
        ///--DROP TABLE IF EXISTS #CTE_CD1
        ///--DROP TABLE IF EXISTS #Temp_UsersMedianPerCourse
        ///--DROP TABLE IF EXISTS #Temp_MedianPerCourse
        ///
        ///--DROP TABLE IF EXISTS #Temp_Users
        ///--DROP TABLE IF EXISTS #QueryF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mean_score_by_studentschool_intakeyear {
            get {
                return ResourceManager.GetString("mean_score_by_studentschool_intakeyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DROP TABLE IF EXISTS #WhitelistedCourses
        ///CREATE TABLE #WhitelistedCourses
        ///(
        ///	CourseCode VARCHAR(24),
        ///	AcademicGroup NVARCHAR(5),
        ///	Instructor NVARCHAR(200)
        ///)
        /// 
        ///INSERT INTO #WhitelistedCourses
        ///SELECT Courses.Code,
        ///		PS_SIS_LMS_CLASS_V.ACAD_GROUP,
        ///		STUFF((SELECT &apos;; &apos; + Users.DisplayName
        ///		FROM UserEnrollments
        ///		INNER JOIN Users
        ///			ON Users.Id = UserEnrollments.UserId
        ///		WHERE UserEnrollments.CourseId = Courses.Id
        ///			AND UserEnrollments.RoleId = 106
        ///		ORDER BY Users.DisplayName
        ///		FOR XML PAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overall_response_rate_by_coursecode {
            get {
                return ResourceManager.GetString("overall_response_rate_by_coursecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DROP TABLE #WhitelistedCourses
        ///--DROP TABLE #Temp_Users
        ///--DROP TABLE #QueryFilters
        ///--DROP TABLE #OverallResponseRate
        ///
        ///--DROP TABLE IF EXISTS #WhitelistedCourses
        ///--DROP TABLE IF EXISTS #Temp_Users
        ///--DROP TABLE IF EXISTS #QueryFilters
        ///--DROP TABLE IF EXISTS #OverallResponseRate
        ///
        ///
        ///IF OBJECT_ID(&apos;tempdb.dbo.#WhitelistedCourses&apos;, &apos;U&apos;) IS NOT NULL
        ///	DROP TABLE #WhitelistedCourses; 
        ///CREATE TABLE #WhitelistedCourses
        ///(
        ///	CourseId VARCHAR(24)
        ///)
        ///
        ///INSERT INTO #WhitelistedCourses
        ///SELECT Courses.Id
        ///FRO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overall_response_rate_by_studentschool_intakeyear {
            get {
                return ResourceManager.GetString("overall_response_rate_by_studentschool_intakeyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- student-result-with-descriptors.sql
        ///
        ///USE LMSTools
        ///GO
        ///
        ///
        ///
        ///IF OBJECT_ID(&apos;tempdb.dbo.#WhitelistedCourse&apos;, &apos;U&apos;) IS NOT NULL
        ///	DROP TABLE #WhitelistedCourse; 
        ///SELECT Courses.Id AS CourseId,
        ///		Courses.Code AS CourseCode,
        ///		STUFF((SELECT &apos;; &apos; + Users.DisplayName
        ///		FROM UserEnrollments
        ///		INNER JOIN Users
        ///			ON Users.Id = UserEnrollments.UserId
        ///		WHERE UserEnrollments.CourseId = Courses.Id
        ///			AND UserEnrollments.RoleId = 106
        ///		ORDER BY Users.DisplayName
        ///		FOR XML PATH(&apos;&apos;)), 1, 1, &apos;&apos;) AS Instructor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string student_result {
            get {
                return ResourceManager.GetString("student_result", resourceCulture);
            }
        }
    }
}
